(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"Lim_Wei_Jun_project_atlas_1", frames: [[0,0,1920,1280],[5766,1082,1280,1280],[1922,0,1920,1080],[3844,0,1920,1080],[5766,0,1920,1080],[1922,1082,1920,1080],[0,1282,1920,1080],[3844,1082,1920,1080]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.HELPWANTEDwillypaperbackground = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.mouse1345876_1280 = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.office = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.outside_office = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.stage_willy_gone = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.willy_at_office = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.willy_jumpscare = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.willy_stage = function() {
	this.initialize(ss["Lim_Wei_Jun_project_atlas_1"]);
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween12 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mouse1345876_1280();
	this.instance.setTransform(-28,-20.1,0.0437,0.0314);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28,-20.1,56,40.2);


(lib.Tween11 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mouse1345876_1280();
	this.instance.setTransform(-28,-20.1,0.0437,0.0314);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28,-20.1,56,40.2);


(lib.Tween10 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mouse1345876_1280();
	this.instance.setTransform(-28,-20.1,0.0437,0.0314);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28,-20.1,56,40.2);


(lib.Tween9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mouse1345876_1280();
	this.instance.setTransform(-28,-20.1,0.0437,0.0314);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28,-20.1,56,40.2);


(lib.time469 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAqBaIgJhyIgBAAIgYByIgPAAIgXhyIgBAAIgJByIgXAAIASizIAVAAIAYB9IAAAAIAah9IAVAAIARCzg");
	this.shape.setTransform(82.3,30.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAaBaIgHgjIglAAIgHAjIgXAAIAnizIATAAIAnCzgAgPAkIAfAAIgQhUIAAAAg");
	this.shape_1.setTransform(68.875,30.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYBbIAFgJQAXgxAEgNQgJAEgGAAQgOAAgJgLQgJgMAAgdQAAgYADgMQAEgNAJgGQAJgIAPABQAUgBAKANQAJANAAAmQAAAagFASQgFASgNAZIgPAfgAgKg+QgEAHAAAOQAAAZADAJQACAJAJAAQALAAACgHQACgJAAgTIAAgDQAAghgPAAIAAAAQgHAAgDAHg");
	this.shape_2.setTransform(57.425,30.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeBNQgKgNABgfQAAgTACgNQACgMAFgOQAFgOAIgRIARgiIAaAAIgWAsIgLAaQAHgDAHAAQAPAAAKALQAIALABAgQAAAigLANQgJANgVAAQgVAAgJgOgAgKAEQgEAHAAAPIAAADIAAAFQAAAUAEAIQADAIAHAAQAPAAAAgdIAAgDIAAgDIAAgGIAAgDQAAgSgEgFQgFgEgFAAQgIAAgDAFg");
	this.shape_3.setTransform(46.85,30.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_4.setTransform(38.875,38.025);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAHBbIAAgxIgvAAIAAgXIAwhtIAXAAIAABtIAKAAIAAAXIgKAAIAAAAIAAAxgAAHgsIgcA/IAcAAIAAg/g");
	this.shape_5.setTransform(30.775,30.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#333333").ss(25,1,1).p("ApblKIS3AAIAAKVIy3AAg");
	this.shape_6.setTransform(60.375,33.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("ApbFKIAAqUIS3AAIAAKUg");
	this.shape_7.setTransform(60.375,33.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,145.8,91.1);


(lib.time_659am = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAoA/IAAhZQAAgSgNAAQgQAAAAAVIAABWIgVAAIAAhbQAAgHgEgFQgEgEgGAAQgPAAAAAUIAABXIgYAAIAAh7IAYAAIAAALQALgNAPAAQAPAAAIAPQALgOARAAQAaAAAAAdIAABfg");
	this.shape.setTransform(88.225,40.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAaBaIgHgjIglAAIgHAjIgXAAIAnizIATAAIAnCzgAgPAkIAfAAIgQhUIAAAAg");
	this.shape_1.setTransform(74.275,37.425);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgYBbIAFgJQAXgxAEgNQgJAEgGAAQgOAAgJgLQgJgMAAgdQAAgYADgMQAEgNAJgGQAJgIAPABQAUgBAKANQAJANAAAnQAAAZgFASQgFASgNAZIgPAfgAgKg+QgEAGAAAPQAAAZADAJQACAJAJAAQALAAACgHQACgJAAgTIAAgDQAAghgPAAIAAAAQgHAAgDAHg");
	this.shape_2.setTransform(62.825,37.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgoBSIAHgVIAEACQAJAFAHAAQANAAAIgLQAIgKAAgTQAAgRgJgJQgHgIgPAAIgPACIAMhWIA7AAIAAAWIgpAAIgEApQAtAEAAAxQAAAcgPATQgPASgWAAQgNAAgQgJg");
	this.shape_3.setTransform(52,37.525);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJAKQgEgEAAgGQAAgFAEgEQAEgEAFAAQAGAAAEAEQAEAEAAAFQAAAGgEAEQgEAEgGAAQgFAAgEgEg");
	this.shape_4.setTransform(44.275,45.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgeBNQgKgNAAgfQABgTACgNQACgMAFgOQAFgOAIgRIARgiIAaAAIgWAsIgKAaQAGgDAGAAQARAAAIALQAKALgBAgQABAigLANQgKANgUAAQgVAAgJgOgAgKAEQgDAHgBAPIAAADIAAAFQABAUADAIQADAIAIAAQAOAAAAgdIAAgDIAAgDIAAgGIAAgDQAAgSgEgFQgEgEgGAAQgIAAgDAFg");
	this.shape_5.setTransform(36.2,37.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#333333").ss(25,1,1).p("ApplwITTAAIAALhIzTAAg");
	this.shape_6.setTransform(61.8,36.85);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("AppFxIAArhITTAAIAALhg");
	this.shape_7.setTransform(61.8,36.85);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-12.5,-12.5,148.6,98.7);


(lib.TIME = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AChCsQgGgFgCgJQgCgGgEhTQgEhTgHhPQgzBfg4ByIgOAdQgFAKgEADQgFAEgFAAQgMAAgMgbIgFgJIhCiFQgcg2gRgfQgEA9gEBZQgEBagFAOQgCAHgFAEQgFADgIAAQgHAAgJgDQgJgDgMgGQATgwAKhBQAKhBAAhQQAAgUgCgQQgCgQgEgQQAIgHAHgDQAGgDAIAAQAYAAA0BsIAgBBQAbA1ALASQAKASACAAQAGAAA8h5IAohRQAQggANgOQAMgOAMAAQAHAAAHADQAHADAIAHQgEAQgCARQgCAQAAAUQAABPAKBBQAKBBATAwQgLAGgLADQgKADgKAAQgKAAgGgEg");
	this.shape.setTransform(478.625,308.675);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("ABDBdIgLgdIiDAAQgUAqgHAYQgIAYAAASIAAADIgIABIgFAAQgQAAgJgGQgHgHgBgMQABgNAvhfQAvheAkhRIgIgMIgKgKQAIgLAIgGQAIgEAHAAQALAAAJANQAJAOANAgIAgBOQBECqAaAZQgJALgIAEQgHAEgJAAQgZAAgfhTgAgRhCIgqBgIBmAAIgZg/IgYg8g");
	this.shape_1.setTransform(438.5,308.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhvCkQgCgHAAgFQAAgaAzglIAWgQQA3grAbghQAagjAAggQAAgdgUgRQgTgSgfAAQgYAAgTAMQgRAMgNAaQgLgHgFgIQgFgHAAgJQAAgZAcgSQAbgSApAAQAyAAAgAcQAgAdAAAtQAAAvgrAxQgqAyhbA+IATAAIAbABQAvAAAegEQAegFAPgJIAGAQIABAOQAAAQgKAHQgLAGgbAAIg6gBIg2gBIgfABIgcACQgEgHgBgGg");
	this.shape_2.setTransform(406.15,308.725);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgBCqQgFgHAAgTIADhTQAChHAAg7IAAghIgCgaIgHADQgaALgEAAQgGAAgEgEQgDgEAAgHIACgLIADgOQAXgEAZgIQAbgJAFAAQAJAAADAFQAEAFAAAPIgCAWQgFBUgBBNQABA/ACAcQAEAbAHAOQgLAGgJADQgIACgJAAQgOAAgEgGg");
	this.shape_3.setTransform(381.6,308.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("EhGXAwkMAAAhhHMCMvAAAMAAABhHg");
	this.shape_4.setTransform(450.375,310.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,900.8,621.5);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AlYBaIFKizIFnCp");
	this.shape.setTransform(126.45,22.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#666666").s().p("A0TEYIAAovMAonAAAIAAIvgAl7AgIFJizIFnCpIlnipg");
	this.shape_1.setTransform(130,28);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,260,56), null);


(lib.replay = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990000").s().p("AAABJIgGgHQgBgCgEgBIAAgCIAEgDIAHgEIAEgDIAKAIQAEACABAGIgDAFIgEADIgGAFIgGgHgAAAANQgDgBgBgBIgBgEQAAAAAAgBQAAAAAAgBQgBAAAAgBQgBAAAAgBIADgDIgBgBIAFgFIACgFIACgDIAEgFIACgCQADgDAIgGIAJgHIACgJIABgBQAAgGgHgHIgBgCIgDABIgEgDIgGgBIgEgBIABgBIAAgBQAAgBAAAAQAAAAAAAAQgBgBAAAAQgBAAAAAAQgCAAgDADIgGAAIgHABIgFgBIgEACQgDAAgCACIgIAFIADAHIgGAIIgGADIgEABIAAAAIgEgBIgBgFQAAgDACgDIADgFIADgDIAEgCIAIgHIAIgEIAFgCIAFgBIAGgDIAJgBIACACIACgBIACAAIAEAAIAJAAIAHACIAFADIALADIAEAIQAEAFAAAEQAAAHgIABIAAAEIgGAHIgCABIgJAIIgDgBIgEACIABACQAAADgFAEQgHAHAAADQAAAFAEADIgCABQABAEACABQgDAFgEAAIgHgBg");
	this.shape.setTransform(183.575,42.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#990000").s().p("AgRA3IgDgBIgDgBIgMgEIgFgFIgFgCQgEgDAAgBIgCgEIgFgGIABgDIgDgIQgBgDAAgJIACgKIACgGIAFgGIADgHIALgKIAKgGIALgHIAEgBIAKgDIAGgBIAJgDQAIAAADAIIAFgDIADADIADACIAMALIAFAHIACAHIACAEIgBABIgEgBIgGACIgEgBIgFABIgJgFIgHAFIgJgCIgGABIAAgBIgMAAIgFABIgGABIgHABIgGAAIgLADIgCAHIgDADQAFADAAACIADAMIACABIgBAGIAFABQABAFACACQADACAFABQAAAEACABQABABAEAAIACAEIADgBIAIAEIADABIAHgCIAJgBIAHgCIAHAAIAJgGIAHgFIAFgHQAAAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIADABIgBAHIgIANIgDgBIgFADIgGADIgMADIgIAAIgEABIgIgBIgFABIgCAAIgFABIgKgBgAgEgpIgIADIgKADIgGAGIgDACIAAABIALAFIADADIAFgIIACAAIAHACIAAAAIAHgCIAFAAIACADIAEgBIAIgCIAIABIAAgCIABgBIgCgDIgCgCQgDgFgBABIgEgCIgDgEIgOAAIgDAAg");
	this.shape_1.setTransform(170.475,44.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#990000").s().p("AgfB0IABgFIABgDIABgEIACgKIAAgIQADgCAAgCIgCgHIgBgHIAAgFIAAgYQAAgFACAAIAFgDIAAgCIgBgBIgDABQAAAAgBAAQAAAAAAAAQAAgBgBAAQAAAAAAAAIgFgHIgHgBIgDgBQgEAAgHAIIgBgCIAGgIQADgEADAAIAHABIAGgEIAAgGIAAgNQAAgEADgFIgEgEIAAgOIAAgLIAAgHQAAgCACgEIAEgHIgBgCIgCgBQABgJAJgLIAGgHIAJgIIAMgHIADgCIAFgBIAHgCIAFABIACABIACgBIADAAQAGAAAEAFIAEAAIgBADIgEADIgCAEIgIAEIgKgFQgFgEgEAAQgEAAgJAFQgDACgCADQgDAGgEALIgBADIgCAIIgDAGQAAAAAAAAQABABAAAAQAAAAABABQAAAAABAAIgBAGIAAAGIAAALIgDAGIAAADQAAACACAFQABABAAAUQAAABgEAEIAAABIADACQADABAAAHIAFAEIAGABIAIADIAKgEIAKgCQAGgEACAAIAFgBQADADAAACIgKAHIgEAEIgCABIgFgBIgFgBIgIABIgFAAIgIgBIgGgBQAAAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAAAABIABAGIABAOIgBACQAAAAgBAAQAAABgBAAQAAAAAAABQAAAAAAABQAAACADADIAAAFIACASIgBABIgDAAIgCACIACADIADAEIgBAFIAAAAIABAHIgCABIAAADIgLAFIgFABIAAgBIgDACIgDgCg");
	this.shape_2.setTransform(158.325,38.425);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#990000").s().p("AgNBaIAAgGIACgFIAAgHIABgPIAAgCQAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIACAAIAAgDIgBgEIAAgFIgDgCIABgEIgBgCIAAgCIACgEIgCgEIAAgBIAAgBIAAgDQAJgCAAgBIAAgBQgCgCgDAAIgGABIABgDIgBgNIgDgDQAAgCAEgEQAJgGAGgDIAFAFIgDAJIgBAHIAAAEIgCAEQAAADADADIgBACIABAHIgBACIAAADIAAAbIABAKIABAGIABAEQAAADgDADIgFADIgHAHIgDAAIgDgBgAgNg/IAAAAQAAgFAIgGIADgEIACgCQAFgIACAAIADgCIADACQADACAAADQAAAAAAABQAAAAAAABQgBAAAAABQgBAAAAABIgNAKIgDACIgFAEIgEACQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAg");
	this.shape_3.setTransform(150.175,41.25);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#990000").s().p("AgKB4IAAgEIAAgEIgBgDIABgEIABgDIAAgEIAAgDIALgIIgLgIIAAgBIABgFIACgEIgDgFIAAgCIACgGIACgHIgEgCIAAgFIAAgEIACgGIAAgDIgBgLIAAgEIADgGIABgHIgEgCIAAggIADgCIACgGIgFgCIABgFQAAgBAAAAQAAAAgBgBQAAAAAAgBQgBAAgBAAIAAgFIAAgGIACgFIAAgBIgBgCIAAgDIgBgBIAKgHIgGgKIgGgJIABgEIABgFIAEgCIAEgDQADgBAEgEIABAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAABIAAACIAAABIACAFIgCALIAAAMIgCAEIgBAFIADAAIABAFQAAADgDADIAAAFIABADIAAAEIAAASIAAASIgDAFIAAADIABAHIAAABQAAABgCADIADAHIABABIAAAJIAAAfIgCACIAAAFIAAAHIAAAEIAEAAIgBABIAEAXIgBAGIABAFIgDAEIABACIgIAFIgDABIgCABQgDACgDAAIgCAAg");
	this.shape_4.setTransform(143.9,38.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#990000").s().p("AgqA1IACgJIABgBIgBgHIAAgCIAEgBIAAgCQAAgBAAAAQgBgBAAAAQAAgBAAAAQgBgBAAgBIAAgDIgBgHIAAgIQAGgCAAgCIgBgDIgDABIgCgBIAAgFIAAgEIAAgDIAAgBIAAgDIAAgCQAAgDACgDQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAgBAAAAIgBgJIgDgFIADgFIAHgEIAHgFQAAAAABABQAAAAABAAQABAAAAABQAAAAABAAIAAADIABAEIAAACQAAABAAAAQAAABAAAAQABAAAAABQAAAAABABIAHgEIAGgCIAGgEIADgCIADgBIADAAIABAAIAJgDIAFAAIADABIADADIACAAIAEgCIABAAQAAAAABABQAAAAABAAQAAAAABABQABAAAAAAQACADABADIgIAHQgDAEgCAAQgCAAgEgEIgEAAIgGgCIgHgCQgBAEgEAAIgEAAIgFACIgCgBIgKAIQgFACAAAJIAAAAIAAAFIAAAEQAAACgDADQABABAAAAQABABAAAAQAAABABAAQAAABAAAAIgBABIACABIABAFIABAZIgBACIgEABIgIACIAJADIADgCIABAHQAAADgDACQgBABgGABIgGADIgCAAQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAgBAAAAg");
	this.shape_5.setTransform(131.175,44.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#990000").s().p("AgRA3IgDgBIgDgBIgMgEIgFgFIgFgCQgEgDAAgBIgCgEIgFgGIABgDIgDgIQgBgDAAgJIACgKIACgGIAFgGIADgHIALgKIAKgGIALgHIAEgBIAKgDIAGgBIAJgDQAIAAADAIIAFgDIADADIADACIAMALIAFAHIACAHIACAEIgBABIgEgBIgGACIgEgBIgFABIgJgFIgHAFIgJgCIgGABIAAgBIgMAAIgFABIgGABIgHABIgGAAIgLADIgCAHIgDADQAFADAAACIADAMIACABIgBAGIAFABQABAFACACQADACAFABQAAAEACABQABABAEAAIACAEIADgBIAIAEIADABIAHgCIAJgBIAHgCIAHAAIAJgGIAHgFIAFgHQAAAAAAAAQABgBAAAAQABAAAAAAQABAAABAAIADABIgBAHIgIANIgDgBIgFADIgGADIgMADIgIAAIgEABIgIgBIgFABIgCAAIgFABIgKgBgAgEgpIgIADIgKADIgGAGIgDACIAAABIALAFIADADIAFgIIACAAIAHACIAAAAIAHgCIAFAAIACADIAEgBIAIgCIAIABIAAgCIABgBIgCgDIgCgCQgDgFgBABIgEgCIgDgEIgOAAIgDAAg");
	this.shape_6.setTransform(117.525,44.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#990000").s().p("AgzB2QAAgEACgHIAAgEIADgEIABgEIgBgCIgCgDIAAAAIABgIIAAADIAAgDIAAgGIAAgDIAAgBIAAgGIAAgKIAAgIIABgDIADgEIABgCIgBgEIgDABQgBgHAAgJIAAgXIAFgBQgCgDAAgDIgEgCIABgGIAAgFIgCgOQAAgDADgCIAGgGQgDgDgHgBIABgFIACgFQgBgCgDgDIABgFIgBgGIAAgGIABgGIgDgNIAAgDIgDgCQABgDAFgCIAJgFQAEgCAEAAIAEACIgIAEIgGAFIALALQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgCAFIgBADIgCABIgBABIgBADIABAEIADgCIACgBIgBAZIAAAEIAAADQAAADgCADIAAAEIACADIABADIgBAIIABAFIAAAIIgBAFIABAGIgBACIABAEIAAACQgCAIAAAHIACAGQAIgEAKgLIAGABIAIgDIAHAAIADABIABADIAEAAIACgDIACgBIAIAAIANACIAFAGQACACAFABIgDAFQACABADAAQADAEAAAEIgBAKQAAAEgBACIgCACIACAFIgDAEIAAABIADADIAAADIAAAEIAAAJIAAABIgCAFIACAKIAAAMIAAABQgEACgEABIgFADIgGACIgFgEIAEgIQACgFAAgFIgCgHIABgCIAAgGQACgEABgHIgDgCIACgQIAAgCIAAgBIgBgHIABgCIAAgBIAAgBIgCgEQgBgCgCgCIgFgCIgHgCIgFgBIgKgBIgDAAIgFABIgMABIgCABIgIAEIgFACQgLAIAAACQAAADAKACIgBAEIgBAQIgEABIAAABQAEAEAAADIABAMIACAEIgCAHIABAEIAAACIAAADIgCACIgJAEIgGAEg");
	this.shape_7.setTransform(102.55,38.55);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#990000").s().p("AgHBRQgDAAgGgFIgDgFIgBgEIgCgFIAAgEIABgKQAAgEADgDIgBgGIgBgZQADgCAAgCIAAgDIgFAAIAAgCIABgCIABgMIgJgCIgHABIgDAAIgFABQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAQAAgEAFgDQACgFADAAIAHABIAAAAIAJgCIAAgEIAAgVIgDgHIgBgCIgBgDQABgCADgDQAFgFAIgCQACgDADAAIABABQABACAAADIAAAWIgCAHIgEAEIABAGIADAAIAAAHIANADIAFABIAIgCIAKgBIAIgDIAEAAIgBAGQAAACgIAGIgDACIgDACIgDAAIgDAAIgGgDIgDgBIgFgDIgHAFIgFAAIgDABIACALIAAAGQgGABAAAEIAAACIAGABIAAASIgEAAQgBAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAIAAAFIAEgBQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIgBAFIAAABIABAIIABAGIAAACIABADIgBADQAFACAFAAQAFAAAEgCIAFgCIAHgHQAGgFABAAIAEABIAAAEIgDAJIgJADIgRAHIgEABIgGADQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAgBIgBAAIgCAEIgEAAg");
	this.shape_8.setTransform(90.4,42.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#990000").s().p("AggA2IgDgDIgFgBQgDAAgIgGIgFgDIgCgDIgBgDIgCgBIgBgCQgDgFAAgFQAAgCADgCIgFgEIAAAAIABgOIAEgKIAHgMIAGgFIACgFIADgCIAKgGIAHgGIARgGQAJgDAPAAIAIABIABADIAEACQAAgBAAAAQABAAAAgBQABAAAAgBQAAAAAAgBQAJACAFAEIAFADIADAFQADAEAHABIAEAIIABAJIACAKIgCAAIAAACIgDADQAAACAEACIgBAIIgCAFIgIAQQgHAJgGACIgIAEIgHADIgHADIgNABIgJACIgKAAIgFABIgQgCgAgVArQAFADAGAAIAIAAIADABIAFAAIAHgBIAHgBIAKgGIAGgDIAGgIIADgHIAEgFIABgCIgCgFIAAgDIADgJIgEgJIgCgHIAAgGIAAgBIgEAAIgGgJIgEgDIgDgCIgHgDQgBgFgDAAIgFACIgEgBIgJAAIgHADIgDgCIgEADIgFAEIgCABIgQAOIgCABIgBAFIgDAFIgDAHIAAACQAAADgFABIABADQAEADAAABQAAABgFADIAAABIABABIAEgBIACAHIAHANIAAABIgCAEQABAAAAABQAAAAABAAQAAAAABABQABAAABAAIACgCIAMAGg");
	this.shape_9.setTransform(76.9,44.925);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#990000").s().p("AgyA1IgBgCIAAgDIABgFIAAgLIACgFIgBgDIgBgEIABgDIAAgCIAAgFIAAgEIABgEIAEgCIgBgBIgFgBIAAgEIAAgFIABgBIgCgMIADgCIgDgFIAAgDQAAgCgEgEQABgFAHgDQAGgFADAAQABAAABAAQAAAAABAAQAAAAABABQAAAAAAAAIABAJQAAACADAFIAHgHIAFgDQAFgFACAAQACAAACAEQAHgGAHAAIADAAIACABIAHgCIAIACIAHABIADACIADABQAEABAFAHQADAFAAAQIgHABQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAAAAAIAJAFQAAAAAAABQABAAAAAAQAAABAAAAQAAABAAAAQAAADgDAFIAAABQAAABADADIAAAFIACAIIAAAHIABAHIgBAGIACAFIgGAEIgGADIgGAEQgEgEAAgDIACgLIABgDIAAgDIADgBIAHgBIgCgBQgDgCgHgCQAAgGACgBIAEgEQADgEAAgCIgJgEIAAgEIAAgIIAAgBIABgEIgCgEIAAgHQAAAAAAgBQAAAAAAAAQgBgBAAAAQgBgBAAAAQgCgDAAgCIgBgBIgEgCIgEgHIgCgBQgDAAgDACQgFAFgFAAIgEgBIgDADIAAAAQgDgHgDAAIgCABIgEABIgIAEQgHAEgBACQgCADAAAEIAAAJIAAAAQAAABAAAAQAAABAAAAQAAABAAAAQgBAAAAAAIgGAFIgBACIACACIAHADIABADIgBADIABAKIgDAEIAAACQAAADADACIgBABIABAEQAAAJACAEIgDAEIgFABIgCAAIgCABIgCACQAAABgBAAQAAAAgBAAQAAABAAAAQgBAAAAAAIgDgCg");
	this.shape_10.setTransform(61.275,44.825);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#990000").s().p("AgfA2IgFgBIgFgCIgHgEIgDgFIgDgBIgCgFIgCgHIACgDIAFgIIAJgJIAJgEIAEgDIADAAIADgCIAJgCIAHgEIAIgBIAEgBIADAAIADAAIAFAAIALgCIAGgBQADgCAAgDIgBgGIAHgJIgJgDIgEAAIgHgIIgLgCIgFAAIgEgBIgCAAIgDgDIgEADIgFACIgMAIIgCABIgCADIgEABIgGgCIgFgCIgEgDIAEgDIADgCIAHgCIAEgCIAJgDIAFgCIAHAAIAGgCIACAAIAEgBIAJAAIAIACIADAAIAIACQACAAADADIgCADQAAABAAAAQAAABAAAAQABAAAAAAQAAAAABAAIACgBIAFgBQACACAAADIADADIAAABIAAAGQACAHABABIABAAIABAGIABALQgEADAAABQAAACAEABIAAAEIAAAEIAAAEIABALQgCADAAACQAAADACACIABADIABAEIgCADIgEADIgFADIgEABIgGABIgDgBIACgKIgMAEIgEABIgDABIgGgBIgFAEIgDAAIgKACIgHAAIgGABIgLgBgAgaArIAFACIADACIAEABIACAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAABgBIADABIADgCIAEABIAHgCIAEgCIADABIAFgDIAHgCIACgEIAGgDIABgEQAAAAABgBQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgDIAAgDIAAgCIAAgHIAAgCIABgFIgEgBIgGAAIgGAAIgDAAIgEAAIgEgBIgCABIgJAAIgCAAIgDAAIAAAAIgFABIgHADQgJAFgFADIgCAEQgBABgFABIAAACIABACIABAHIADAEIgCADQgBABAAABQgBAAAAABQAAAAAAAAQAAABAAAAIACADIADgEIAHAEg");
	this.shape_11.setTransform(46.1,44.95);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#990000").ss(5,1,1).p("AyRmUMAkjAAAIAAMpMgkjAAAg");
	this.shape_12.setTransform(117,40.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AyRGVIAAspMAkjAAAIAAMpg");
	this.shape_13.setTransform(117,40.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.5,-2.5,239,86);


(lib.mouse_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.mouse1345876_1280();
	this.instance.setTransform(0,0,0.0515,0.0313);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,66,40.1);


(lib.help = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhPCnQgFgBgDgDQgDgDgCgEQgDgFAAgFQAAgIAOgJIAFgEIADgCIAEgBIAFgBIADABIAEACIAEADIAEACQAPAAAAANQAAAHgEAEQgQAQgQAAQgFAAgEgCgAhBBCIgBgMQAAgJADgIQACgIAHgNIAFgKIACgGQAMgIAMgHQANgGAVgIIATgHIALgFQAFgCAEgFIAHgKIAEgMIACgMQAAgHgDgLIgFgRQgCgEgEgDQgFgEgFgCIgMgDIgKgBQgRAAgJADQgLADgJAJQgDADgBAFQgBAGgCACQgCADgJADIgMABQgMAAAAgNQAAgLAMgOQANgOAQgJQARgJALAAIAHgBIALAAIALAAIAHgBQAFAAAJADQAJACAEADQALAIAHAHQAHAHAEAHQADAIABAKIACAXQAAAOgCAMQgDALgEAJQgEAJgHAHQgGAHgIAFQgQALgXAGIgWAIIgWAIQgGASgFAXQgDAKgHAEQgHADgNAAQgCAAgBgJg");
	this.shape.setTransform(165.475,44.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ah3BIIAAgHIABgaIAFghIACgMIACgOIAEgaIAEgVIACgHIACgIIAEgSIAGgOQAEgHAGgGQADgBAEAAQAIAAAEAFQAEAFAAAIIgBAHIgEALIgEAMIgCAHIgEAMIgCANIgCAOIgCAOIgCAOIgBALIgBAKIARgHIAWgJQAagKASgKQAUgJATgMQANgHALgJQAMgKALgLQAXgXAAgTQAAgJgSgFQgJgDgJgBIgSgCIgRgBIgPAAQgpAAgwAJQgXAFgqAOQgFACgDAAQgEAAgDgDQgDgDAAgEQAAgLAGgGQAGgHALgFQANgFAagGIAagEIAbgEQAbgDANAAIAWAAIAWABIAUACIAVAEQAWAFAPAMQAOALAAAUQAAAHgGAPIgGANIgFAKQgQAWgiAXQgjAXgjARQgVAMgXAJQgXAKgXAHQgBACAAAGIAAAHIABARIABAaIACAcIABAUQAAAJgFAEQgFAFgIAAQgYAAAAhmg");
	this.shape_1.setTransform(137.275,45.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhyChQgIgGAAgJIAAgMIACgPIADgSIAEgTIADgRIAEgVIAEgXIACgRIAFgbIAEgZIADgXIADgaIACgdQABgNACgJQACgIAFgFQAFgEALgBQAGAAAEACQAEADACAEQADAEABAEIACAKIgBAKIgFAVIgFAbIgHAeIgFAdIgFAYIgDAUIgEAXIgDAVIgEAVIgCARIAAAMQAAAEADADQADAEAEAAIANgCIARgEIASgEIASgGIAGgBIANgDIAPgDIAQgDIAMgCIAIgBIAIAAIALgCIAOAAQAIAAAHACQAEABACACQACADAAAEQABAEgBAEIgEAGQgEAGgHADQgGAEgFAAIgIAAIgJAAIgKAAIgHAAQgOAAgPADQgPABgPAFIgcAHIgbAHIgYAGQgLADgIgBQgNAAgHgFg");
	this.shape_2.setTransform(104.8458,45.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AiJCkQgEgCgDgEQgDgEgCgHQgBgHAAgKQAAgKACgLIAGgbIAGgbIAGgaIAEgbQACgMAAgOIABgTIADgUIACgUIABgUIgBgFIAAgEQAAgKAHgLQABgDAEgDIAJgFIAKgEIAIgBIAHAAIALADIAMABIAHABIAKABIANAAIAPAAIAOgBIAfgCIAfgDQAKgCAIgDIAQgEIAPgEQAHgCAIAAIAFABIAFAEIAEAFIABAGIgBAFIgCAGIgDAFQgCADgCAAIgLAFIgLACIgoAHIglAEIggACIgXABIgKAAIgIAAIgIAAIgHAAIgRAAIgMAAQgDAHgBALIgCAXIgBAXIgCATIAIAFIAGACIAHABIAIAAIAMAAIANAAIANgBIALgCQAHgCAHAAIAMgBIANAAIAOgEIAKgEIAIgDIAIgCIAIgBQAEAAACACIAEAHIACAIIAAAJQAAAFgDADQgEADgEABIgKAEIgHACIgNABIgRACIgRAAIgOABQgOACgQABIggABIgPABIgNADQgBAAgCAGIgEANIgEARIgEASIgEAYIgCAPIADADIAEACIAOAAIAQgBIAQAAIAOgBIAegDIAdgDIAcgEIAWgEIADgBIAIgCIALgDIAKgDIAJgCIADgCQADAAADACQADACACADIAEAHQACADAAAFIgCAFIgFAGIgHAGQgEADgFABIgUADIgTADIgWADIgYACIghAEIgfADIgaAEIgQADIgLACIgMADIgLADIgJABQgFAAgFgBg");
	this.shape_3.setTransform(73.875,44.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AiICzIgIgHIgHgJQgCgFgBgEIABgJIACgMIADgKIACgJIAGggIAGgnIAGgrIAGgvIAFgvIAFguIACgGIAEgEQACgDADgBQAEgBADAAQALACAFAFQAFAFAAAIQACAQgDAQIgHAiIgGAiQgEARABAOQAAADADACIAHACIAIABIAHAAIARAAIAegBIAigDIAjgDIAbgGQALgDADgDIADgKIAEgSIAEgaIAEgeIACgfIABghIACgFIAFgGIAHgEQAEgDAEAAIAHABIAHADIAGAFQADADAAAEQAAAIgBALIgFAbIgGAgIgGAkIgHAmIgEAnIgBAIIgBASIgCAYIgBAZIgBAaIAAAWQAAAFgDAGIgHAJQgEAEgEADQgFACgDAAIgGgBIgGgDIgFgGQgCgEAAgEIABgMIACgUIADgYIAEgaIABgWIABgRQgBgFgDgDQgEgDgFAAIgSABIgYACIgXABIgSABIgIAAIgQABIgUACIgTACIgQACIgIABIgCAGIgDAKIgCAOIgCAQIgCAPIgBALIgBAZQAAAMgCAKQgCAJgEAGQgFAHgHAAQgDAAgEgDg");
	this.shape_4.setTransform(38.0229,43.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AumHHIAAuNIdNAAIAAONg");
	this.shape_5.setTransform(93.5,45.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,187,91);


(lib.gameover = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#990000").s().p("AkdFqIACgDIANgbIABgTQAIgoABgQIgGgEIgBgCQAbgNAFgEQAFgDAAgFQAAgKgigTIAJgCIABgPIAAgBIgDgIQgDgIAAgLIAGgzIAAg2QAAgDAFgIQAEgFADgHIgNgGQgDgSAAgJIABgIIACgcIAAgCIgFgjIAEgEIAJgHIAAgGIgLgHIABgOIgCgdIAIgKQgGgHAAgEIABgIIgHgBIAAgBIAVgjIABggIALgNIgiggIABgaQAAgLgJAAQgEABgFACQgEgEAAgDQAAgGAGgFQADgDAEAAIAJACQAIgHAKgFQASgJACAAQAEAAAGAJIAEgBQAEABAIADIAIgHIAVABIAPACIAngEIAAAAIAIABQAPACA7ABIAKACIASACIAGAAQAEAAAHgGQAKADARAAIAVAEIAOABIAJADIAPAAIAMACQAQACARAHQAJADACAJIgCACIgGAAIAAAJQAEAEAEAAIACgCIAAgEQAAgEAEgEQAEABADACIAEAEQALAHAAAGQAAAMgDARQAIABAAAFQAAADgHAMQgHAKgJAFIgEAGIgdAbIgTANQgCADgDAIIgNAJIgHgCQgFAEgGACQgIAEgHAIIgMANQgDABgJABIgHAHIgKgEIgFAMQgOADgIAGIACACQgJAKgHAFIgQAEQgEABgDAGQgOAIgGAGQAIACABABIAOAdIAPAPIAFAKIgHACIAGAGIAEAAQAHAAAJAIIAHAKIAJALQgHAGgBAGIAEAEIAQACIAGAJIAJAKIAOAZQAGALAcAgIAMASQANAPACAFQAFAKAAAEIAAAFIAAABQAAAEABADQABACATAKQAJAGAKALQAcAlACAEQADAGAAAKQAGAGAMAHIAGgBIAAAAIAEABIAGALQACADANAGQAGAIACAAIAOgGIANABIAGgCQADADAAAEQAAACgCAEIgRAHIgNAIIgMADQgIABgQAGIgMAFIgKAHQgCAAgIgIQgDgDgIgDQgEgKgOgVQgDgEAAgMIgYgOIAHgOQgIgLgJgFQgHgHgQgZIABgKQgMgFgHgIQgVgUgCgYQgFgJgOgGQgIgGgPgZQgIgCgFgGIgNgQQAAgLgEgFQgIgMgFAAIgIABIgMgUIgcgkQgMgQgMgLQgZgXgHAAIgzAUIgBAAIgLgCIgFAPIgBAFIABAKIAAAJIACASIgCALIAAAKIAAAQIABAiIADALIAAAfIACASQAAADgDAFQgDAGgBAGIgKADIADATQAGABAEADQgDAGAAAFIADAMIABADIgBAJIAAAGIABARQgKAEAAAJQAAAIALABIgCAGIABAYQAAAGgFAJQgDAFgIAEQgJAGgBABQgDADgDAFIgNgCQgNARgSABQgDAAgIgFgAjLirIABAjIAAAQIABAUQgCALAAATIgHACIAAAHIACAAIAKACQAGgFAFgBIANgDIAHADQADAAAFgDIACgDQAIgBAVgIIAKgBIAWgOQALgGAOgIIBNgqQAWgKAJgGQAGgEALgMIAQgMIANgNIAMgFQACgBAKgPQAIgFACgDQADgIAAgGIAAgGIgCgHIAAgFIAIgEIAAgDIgOgEIgGgMIAAgFIgCgCQgCgDAAgEIAAgEIgMgEIgBAHIgMgFIgUgGQgHgCgFgEIgJABIgWgHIgdAAQgEABgHgGQgHACgSAAIgNAEIgSgGIgPgEQgLAAgWANQgHADgGAAIgEgBIgNgTIgOAFQgSACgDACQgHAEgBAGIgBAeQAAAEgGANIgFgCIgCAGIAAABQgBAEAEAEQAKALACACIAAAXIAAAGQAAAEgCAEQgDAFAAAIIgIAHQAAAKgFAGIABACIAHgEg");
	this.shape.setTransform(735.975,258.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#990000").s().p("AlXFyIAAgHQAAgDADgIIADAAQAEAAAEgDQADgEAMgYIgBgWIABgCIAGgHIgCgJIAAgDQACgYAAgeQAAgKAFgTQABgDAFgDQAEgCAAgGIACgMIgFAKIgDAAQgCgGgEgFIAAgKIgBgRIAAAAIAJgMIAGgVQACgDAPgGIACgBQAAgDgegIIANgGIAAgFIgJgEQgBgHgGgEQAAgJACgJIgEgjIAfgXIgfgoIAYgKIgZgJIAJgGQAAgKADgKQgEgDgFgEIgEgEIgCgRIgBgRIAAgFQAAgEAFgHQgBgEgEAAIgEABIgBgNQAAgHAHgGQgJgIAAgIIAAgwIgCgfIgDgWIgGgFIAAgSIgNACIAAgCIgCgBIgHAAQgFAAgFgBQABgLAEgGIAIAAQAFgIAGgEIAOgJQAGACADAAIAJgCIAGgBIAnADIANABIAIgCQAOAKAEAAIAFAAIAIABQALgGAJgBQAEABATAGIARAEIARAEIAGgCQAFgCAEAAIBRABIADAEIAVACIAGgHQAZgBAXgDIAJAAIALAAIAPACIA3gLIAXgCIARgCIAPACQAAAHgGAHIgEAFIgUAKIgLAJQgJAHgEAAIgBAAIgSgBIgPgGIgEAAIgDAAIgTAAIgYgCIgWABIgQAAIgXAFIgdgDIgOAAIgJgBIgYACIgUAAIgJAEIgtgDIgMACIgJgDQgGgBgcgBIgHAAIgQABIgMgCQgDgBgGAIQAGALAAALIABAQQgIAJgFAAIgFgBIgBAJIABAEIAGAGIAKAIIgDAPIAEAYQAJACAVACIAaAFIASAAIAPADQAPAAAQACIANABIAMgBIAQgCIAPADIADAAIAUgBIAKAAIAdgBQAcgBAPgDIADgBIAMABIANABIAAgFQALgBACgDIACgBIARAWIAIgOIAJgHQAJgHAEABIALABQgBANgCAAQgBAEgKAFIAAALQgIAEgFAHIgNADQgGAAgFgGQgPgPgCAAIgOATIgBAAIgDgBIgLgEQgEADgRACIgUgDIgYADIgOgEIgRAAIgIgBIgdAFIgcgFIgjABIgMgDIgOAAIgMAAIgKADIgPAAQgNADgMAAQAEAKABAMIABANIAAAiIACAWQAAADgFAGIgGACIgBgBQgEAHAAAFIACAGIADgBQAHAFACAEIAAAMQAAAGgHAFQABAJAGAOIABANIAAAHIgJAFIgBAIQAAAHANAHIgEAHIAEASIABAPIABAKIgBALIAAAPIgCAIIgBAZIAAALIACAJIgPAIQAAAHAEAJIADAAQAEgDACAAQAEAAAFAFQgFAOAAAFIADAMIAAAcIADAhQAAAPgVAQQAAALADAFQABACAFACIAJAGIAPgNIARAAIAfgGIAOAAIAVABIAOAHIADAAQAGAAAJgIIABAAIABAAIALAPIAPgNQADgEACgBIACAAIAsADIAPAAIAOAAIAEABIAOgCIADAAIAEAAIAZABIAPgBIAHAAIBGgBIAFAAIAFgBIAEAAIALADIAMAAIAEANIAMADIAAgOIAAgBIAEgCQAMAUABgBIAWgRQAFgEAFAAQAFAAAGAGIAMgDQAHAAADgCQABgGADgBIAJgFIAQAAIAogJQAJgFADAAQAGAAAAAJQAAADgDAIIgGAOQgGADAAABIgDAIQgKAOgegBIgNADIgVgTIgcAWIgPgEIgVAAIgOgDIgSAAIgWgCIgFABIgGgDQgKAFgGAAIgbgEQgFgBgUAAIgTABIgPABIgigGIgGACIgIgCIgGAHIgKgBIgpAAIgQAAIgYACIgIgCIADgHQgKAAgKAEIgCAKIgHAAIgBAAIgBABIgBAAIgBgBQgJgEgIAAQgHAAgEACIAAAAQgBAAgLgOQgEgEgEAAQgDAAgZAPQgGAFgHAAIgTgFIgEAAIgZAEIgUABIgeAFQgEAAgJgCg");
	this.shape_1.setTransform(663.975,257.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#990000").s().p("AAQF1IgJgiIgPglQgLgkgCgDQgDgFgLgJQAAgKgBgCIgFgNIgFgOIgJgPIgGgOIgGgKIAEgEQADgCAAgGQADgDAAgEIgIgCIgFgPQgEAAgGAFQAAAAgBAAQAAABgBAAQAAAAgBAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQgBgCAAgPQgBgEgVgwIgEgaQgJgCgDgEIgFgQQgNgcgCgIIgFgSIADgHQAAgEgEgGIgIACQgIgIgBgCIgFgRIgQghIgBgIIABgIQgMgHAAgCQgCgDgGgPQgBgFgIgOIAJgDIABgMIgDgDIgIgCIABgfQAAgcgFgcIgDgLQgDABgGBYQgGgLgOggQgEgIAAgEIAAgGIgHgIIgOgdQgQgdAAgDQAAgCADgGQAKgBACgCIALgJIAOgKIANgKQAEgCAGAAIAIABQADAKARAlIAAADIgCASIgHABIgHAPIAIABIABAAIAIgDIABABIABAIIAIAEIAFAVIAFABQACALAKAUQAGAVAEAGQgGAHAAAFIAEAGIAIAOIAHABQAKAjADABIALAWIAHAQQAKAWAAAGQAAAEgEAIIAAAAIgDADIACAFIAGgCIAFAEIAEgJIABACIACAAIAEAQIAPAbQAHAUAPAcQAHANAAAJQAAAHgKAIIAHAPIALAAIAFAJIAIALIADANIAJARQAGAPAJAQQAFAJAKAbQABADAGAGQASATAAADQAAAFgHAIIAIAHQAHgHACgDQACgDACgKIAFgWIAMgmQAJgiADgGQADgHAIgJIAIgEIABgDIgCgJIgBgCQAAgGADgIIAIgWIANgrQADgLAGgKQANgUAAgIIgBgIIAFgGIAHgdIAKgfIACgOIAJgWQACgFALgCIgCgJIACgIIgIgKIABAAIAXg8IAFgPIAEgLIAHgaIgDgOQAAgFAFgMIAIADIABgFIgCgGIAAgDIAFgUIAAgKIAFgNIAUgEQAHgDAIgIQAFgEAFgBQALAGAAAFQAAADgFAGQgIAMgFAUQgFAUgPAjIgFAOIgRA2IgFAFIgSBBIAAAAQgFACgCAFIgGATIgBAKIgDAIQgGAYgEANIgGAQQgEANgDADIgHAGQgCACgBADIgDARIgIAHIAAADQAGAFAAADIgDAGQgFAIgGAYIgHAYIgDANIgJAUIgIAfQgPAmgEASQgCAJgEADIgLAGIAAAHIADADIAHABIgNAvIgBAMIgCAJIgCARIgGAbIgIgBIAAAOQgEADgJACQgXALgFABIgEgGg");
	this.shape_2.setTransform(591.175,257.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#990000").s().p("AhyGDIgNgCIgNgDQgMgBgCgBQgDgBgCgFIACgBIgFgHQgHAAgJADIgCAAQgFAAgCgIIgHgbIgDgJIgBgDQgDABgEAmQgKgHgXgMIgegTIgCgIQgBgDgHgCQgBgIgBgEIgGgNQgIAAgIgEIgHACQgDAAgKgMIgMgQQgBgNgCgCIgIgHIgCgEIgIgPIgSgcQgHgUgBgDQAAgDAGgGIAGAAIgBgMQgDgDgGgCQgJgCgCgSQAAgPgDgJQgDgNgBgpIAAgBIABgOIABgXQAAgMAIgIQAFADAEAAQAEAAAAgHQAAgFgLgJIABgLIAIgTQAMgsAXghIASgkQASgaAKgMIAEACIAGgGIAAgEQAAgHAIgKQAHgHAUgQIAHgLIAEgBIAKADIAHgLIgCgEQALgIAMgCQACgLAEgDQACgDAXgJQALgGADgDQAHgGAGAAIAHgIIAUgJIAPgIIAMgDQAOgJAPgDQANgDAagBIAUgCIAOgCIAPgCIAMAAIAIABQAWABAFABIAUAFIAkgDIADADQAGAHAEADQACACARAAQAGABANAGIAJACIAIADIAGACQADABADAKIAHgEQAPAEAFADQAEADAFANQAGgFAEAAQACAAAgAYQALAIADAEIADAGIAHAKIgHALIADAAIAAAMQAGgEADAAQAGAAAIAKIAHAAIAGAMQAHAKACAIQAKANACAGQgGAGgBAGIAAADQAPAMAFAJQACAFAAAaIAFAVIABANIADAVQAAAEgCACIgJAIQgCACAAANQAAAIAEAEIAJAHIAEAHIACAHIgCAIIgBAJIAAAEIABAZQAAAFgIAYIgBAHIgFALQgEATgCAFQgDAEgFAFIACAIQgIAFgBADIAAAEQABAFgMARQgZAhgUAUIgWAcIgPALQgDACgOAOQgHAIgHAEIg/AnIgLAFIhkAuIgOADIhOAVIgDABIhAAHgAgKFjQADAAASgHIANgCIAWgIIAagBIALgHQAZgMAIgFQAIAFAEAAQAFAAAFgIQgFgGABgEQAAgDAMgFIAQgJQAEgEARgIIAJAGQAGgLAKgFIAAgJQAKgFAbgXIANgKIAOgSIAMgOIALgUIAKgQQAJgWAFgIIgBgJQABgJAGAAQACAAADAFIAFAGIAIgJIADAAQAIAAAAgEQAAgFgDgGQgKAFgGABQgEgGAAgEIADgVIAAgPIAhgIIgkgOIASgCIASghIgCgCQgHgHgMAAIgRABQAOgDAAgJQAAgKgQgIIABgMIgDgZIgDgXQgGgHAAgCIgIgnIgGgLIgGgNIgIgMQgKgbgOgLIAAgNQAAgFgCgHIgPAEQgGgIgNgMIgMgMIgdgQQgMgHgHgLIgGADQgEAAgGgGIgHAAQgKAAgUgMIACgMQgBgHgOgEIgHAIQgBAEgEADQgJgDgOgCQgVgHgCAAIgPACIgDgSIgCATIgLgEIgXAEIgJABIgNgBIgQgBIgQACIgUAEIgWALIgTADQgDABgFAIIgIgBIgCAIQgOAGgIAFIAAAHQgSAGgRAQQgYAVgOAGIgGANIgbAcQgDAIgFAHQgFAFgSAfIgQApIgHAJIgEAUIgEAHIgBAQIgIARIgBADIABADIAAAPIAAA6IAAADIAAACIACAIIAAAFIAAAUQAAACAEAGQAHAJACALIADANIgBALQAAACANASIABAEIgBAJIAEAGIgDABIAKADQAFAOAHAGQAEAEABAHIAHAJQgHAJAAAEQAAAEAFADQAEAEAEAAIANgEQAEAHACABIAJAIQALALAPAIQgDAIAAAGQAAAFAFADQAFAFAIAAIAGgBIARANQABAIABABIAGADQAGABAJAGIAPAHQAHADAJAHQAHAAAWAGIAaAFQAKAEACAAIAHgBIAGAAIAIAAIAFAAQADAAAHgCQAGAIAGAAgAlECeIACAAIAGACIADAAIgBAAIgGgCIgEAAg");
	this.shape_3.setTransform(516.45,256.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#990000").s().p("AlXFyIAAgHQAAgDADgIIADAAQAEAAAEgDQADgEAMgYIgBgWIABgCIAGgHIgCgJIAAgDQACgYAAgeQAAgKAFgTQABgDAFgDQAEgCAAgGIACgMIgFAKIgDAAQgCgGgEgFIAAgKIgBgRIAAAAIAJgMIAGgVQACgDAPgGIACgBQAAgDgegIIANgGIAAgFIgJgEQgBgHgGgEQAAgJACgJIgEgjIAfgXIgfgoIAYgKIgZgJIAJgGQAAgKADgKQgEgDgFgEIgEgEIgCgRIgBgRIAAgFQAAgEAFgHQgBgEgEAAIgEABIgBgNQAAgHAHgGQgJgIAAgIIAAgwIgCgfIgDgWIgGgFIAAgSIgNACIAAgCIgCgBIgHAAQgFAAgFgBQABgLAEgGIAIAAQAFgIAGgEIAOgJQAGACADAAIAJgCIAGgBIAnADIANABIAIgCQAOAKAEAAIAFAAIAIABQALgGAJgBQAEABATAGIARAEIARAEIAGgCQAFgCAEAAIBRABIADAEIAVACIAGgHQAZgBAXgDIAJAAIALAAIAPACIA3gLIAXgCIARgCIAPACQAAAHgGAHIgEAFIgUAKIgLAJQgJAHgEAAIgBAAIgSgBIgPgGIgEAAIgDAAIgTAAIgYgCIgWABIgQAAIgXAFIgdgDIgOAAIgJgBIgYACIgUAAIgJAEIgtgDIgMACIgJgDQgGgBgcgBIgHAAIgQABIgMgCQgDgBgGAIQAGALAAALIABAQQgIAJgFAAIgFgBIgBAJIABAEIAGAGIAKAIIgDAPIAEAYQAJACAVACIAaAFIASAAIAPADQAPAAAQACIANABIAMgBIAQgCIAPADIADAAIAUgBIAKAAIAdgBQAcgBAPgDIADgBIAMABIANABIAAgFQALgBACgDIACgBIARAWIAIgOIAJgHQAJgHAEABIALABQgBANgCAAQgBAEgKAFIAAALQgIAEgFAHIgNADQgGAAgFgGQgPgPgCAAIgOATIgBAAIgDgBIgLgEQgEADgRACIgUgDIgYADIgOgEIgRAAIgIgBIgdAFIgcgFIgjABIgMgDIgOAAIgMAAIgKADIgPAAQgNADgMAAQAEAKABAMIABANIAAAiIACAWQAAADgFAGIgGACIgBgBQgEAHAAAFIACAGIADgBQAHAFACAEIAAAMQAAAGgHAFQABAJAGAOIABANIAAAHIgJAFIgBAIQAAAHANAHIgEAHIAEASIABAPIABAKIgBALIAAAPIgCAIIgBAZIAAALIACAJIgPAIQAAAHAEAJIADAAQAEgDACAAQAEAAAFAFQgFAOAAAFIADAMIAAAcIADAhQAAAPgVAQQAAALADAFQABACAFACIAJAGIAPgNIARAAIAfgGIAOAAIAVABIAOAHIADAAQAGAAAJgIIABAAIABAAIALAPIAPgNQADgEACgBIACAAIAsADIAPAAIAOAAIAEABIAOgCIADAAIAEAAIAZABIAPgBIAHAAIBGgBIAFAAIAFgBIAEAAIALADIAMAAIAEANIAMADIAAgOIAAgBIAEgCQAMAUABgBIAWgRQAFgEAFAAQAFAAAGAGIAMgDQAHAAADgCQABgGADgBIAJgFIAQAAIAogJQAJgFADAAQAGAAAAAJQAAADgDAIIgGAOQgGADAAABIgDAIQgKAOgegBIgNADIgVgTIgcAWIgPgEIgVAAIgOgDIgSAAIgWgCIgFABIgGgDQgKAFgGAAIgbgEQgFgBgUAAIgTABIgPABIgigGIgGACIgIgCIgGAHIgKgBIgpAAIgQAAIgYACIgIgCIADgHQgKAAgKAEIgCAKIgHAAIgBAAIgBABIgBAAIgBgBQgJgEgIAAQgHAAgEACIAAAAQgBAAgLgOQgEgEgEAAQgDAAgZAPQgGAFgHAAIgTgFIgEAAIgZAEIgUABIgeAFQgEAAgJgCg");
	this.shape_4.setTransform(418.525,257.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#990000").s().p("AERFyQAFgNABgOIACgJIgEgMQAAgGALgGIgBgKQgMgKAAgIIABgIIAHgcIgIgZIAAgBIABgeIAAgBQABgHgFgXIgBgLIAJgBIgDgQQAAgDgJgBIgEgUQgCgHAAgRIAAgNIAAAAIAAgFIAAgBIAEgOIgCgLIgCgKIgDgHIgDgnIgCgPIACgiIgCgMIAdgLIgdgIQAEgGAAgCQAAgPgMgDIAAgBQAAgIANgDIATgDIgfgRIAAgUQgBgDgGgHIgEAAIgDAKIgHAQQgBAAAAAMIgJAIIAAAFQAAAFgJAPIgFAPIgGAMIgEAPIgIAMIgDAMIgDAGIgCAPIgRAmIgHAYIgJAHIgBAMIgKAFQAAAJgGAWIgLAEIABANQAAASgQAMIABAHIgCAEIgIAQIgJARIgKAcIgGAMIgFANIgHAKIgEAKQgFAIgDAMQgPAlgGASIgIAAIgEAAIgJABQgDAAgDgEQgDgDgMgeIgPgUQgEgFgDgLIgEgQIgIgCIgKgeQgDgJgPgXQgFgJAAgKIAEgNIAAgBQAAgFgFgFIgNADIgKgUIgIgQIgEgGIgDgLQgJgRgEgKIgFgFIgNggQgQgagDgKIABgBIAGgCIgGgMIgFgMQgFgRgCgBIgEgCQgDAAgFACQgVgnAAgIIABgIIgKgLQgEgEgBgEIgBgPQgGgIgCgJQgBgHgEgIIgFgBQgLgZgLAAIgFABQADAJAAALIACAPIAAASIADAWIgBAIIAAAJIACAaIAAABIgCALIgGAEIACANIgFACIAAAKQANABAAAGIgBALIgBAHIAAAgIgBAOIABAPQAAAEgGAGIADAVIgGADQgCAEAAAFIAHASIAAABIgBAJQgCAGAAAJIABAJIAAARIgDAUQgCAMAAAPQAAAKAEAKQgCAFgFADQgRAJAAAIQAAAEAHAIIAIgKIADAAIACADIgBAIQAAADAFAKIAAABQAAAFgRAGQgPAGAAAFQAAAFAMAFIAVAHIgCALIAAAIIgKAHIACAIIgBADQgBACgXAGIgNAIIgZAJIgFgCIAAAAIAAgEIAAgBQAAgBAHgJQADgEAOgJQAJgGACgEIAGgMIAGgIIgfgTIADgDQAGgGAAgMIAAgYIAEgLIAAgHIgCgJIADgJIgDgNIAHgeQAAgGgDgQQAKgGAAgIQAAgEgGgCIgBgeIABgPIADgZIgCgJIALgDIAAgEIgDgIIgGgNQAHgEACgDQABgEABgHQgGgIgCgEIAXgPIgBgBIgYgIIALgfQgDgNgMABQAEgSAAgDIgBgJIAAgMIgBgaQAAgKAGgHQgJgNAAgKQAAgGAEgIQgGgHAAgDIACgGQABgDAAgTIABgKIgFAAQABgHAAgVIAFgSQAAgEgHgPQgIgBgEgEQAAgEAFgGQALgNAQgKQAVgMAIgIIAGAAQAPAUAEAJQADAKACACIAHAFIABANIAGAVQgWADAAAGQAAAGANAGQAJgGAHgBIACABQABATAGAKQAFAIAAAFIAAAAIgBAMQAAAIAMAGIAEAPIABAEIgBAJQAOAIAAAGQAAAHgOAJIAGATIADAAQAIgKAFAAIAJABIABADIAAAGIAAACIAAABQAAAEADAFQAQAcACAKIAFARIAAADIgBAKIgGAAIgBABQAAAEAEAGIAGgCQAEAAABADQACACACAMIAKADQABALAHAJQAIANAKAbIAGALQAHANADAQIABAFIgBAKQAAACAHAGIAGAJIAKABQADARADAHIAIADQAEANANAXIASAnIAGAMQAHAOADABQABABAEAAQAGgIAIgOIAMgWIAEgIIAHgNIADgMIANgXQACgCAKgGQAFgEAAgDIAAgDIgFgOIAIgKIAFgMIAKACQAEgGAAgCIgBgIIAAgIQAAgHACgEIASgwQAGgUACgDQADgEAJgIIgDgMQAAgEARgnIAIgYIAMgaQADgFALgBQgEgIgBgKIgBgEIAEgPIgBgIIApg8IACgRQAJgOADgCIASgNIAEgFIABAAQgBgGghgCIgKAAIgMgSIAGgOIAHgDIANgIIAMgEQAPgKAGgCIAXgFQADAPAAANIABAKIABAFIABALIgBAWIAAAOIgCANIAAALIAAAGIADAHIgJAAQgGgBAAAGQAAAFANADIgGANIACACIAEAAIADACIAAAMIgBANIADAeIAAADQAAAEgIAOQgBABAAALQAAAEADAFIAKgCIAFAEQgEAKAAAMIADAXIACBGIABAJIABAQQAAADgCAFIgKgBIAAAEQAAAEgEAIQAIAHAIABQACAIABAJIAEAeIADASIADAFIgGASIgCALIAPAKIAAAOIAAAHIgCAJQAAAEAEAIIgMACIgFAQIAKAGQAFABADAMIACANIAFAJIAGAbQAAASADAVIgRASQgXARgWgBIgJADIgGABQgCAAgFgCg");
	this.shape_5.setTransform(335.875,257.25);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#990000").s().p("AE4FbQgCgIgGgJQgKgeAAgDIAAgGQgHgHgCgFIAAgMIgBgGQAAgEAEgJIgMgLIAHgHQAEgDAAgCIgBgGIgTABQgJgMgDgIQgDgEgEgUIgGgOQgEgZgDgEQgGgOgPgBQgOABgCAdIgDABQgFAAgGgFQgMgJgMgBQgGgCgLgFQgNgGgJAAIgWAEIgLgCIgMABIgLAAIgLACIgSAAIgPAAIgGAAIgYgFIgLADIgOgEIgTAFIgVADIgLgMQgNABgMAIIgRACIgHABIgLgBQgKgCgIAAQgFAAgOADQgIADgKABIgFAJQgFAMgKALIgSAgIgHgCQgDADAAACIABAJIABAHQgIAIAAACIgTAmIgLASIgEAGIgVANQgBAAAAABQAAAAgBABQAAAAAAABQAAABAAABQAAADAJAIIgGASQgJAEgDADQgGAEgGANQgLAFgDACQgGAEgCAAIgIgEIgGgBIgFAAQgHgHgJgDIADgGIAMgHQADgDAMgPIAJgIQAEgDADgGIAAgHQAAgIAKgJQAPgOADgFIAWgmIAHgDIACgCIAAgHIABgGIAJgMIAng9IAAgEIgEgCIgFAAIgDABIgHgBQgDgHAAgEIAFgJQADgKAEgFIAJgNIALABIARAGIABgBIABgGQAAgDgCgGQAIgFAAgCIAIgPQADgFANgLQABgKABgCIAPgOIAJgUIAWghIAZgzIALgLQAAgHABgBIALgQIABgDIgBgGQAEgDADgIIAIgOIAIAMIACgHQAAgCgDgHQADgJACgCQAIgMAAgCIAAgIIAFgJQABgCAHgRIAEgKIARgCIgCgFIgKgFIAAgGQAGgFADgFIgFgFIAAgBQAGgGAFgJIAIgQQgCgFAAgEIAAgCIAAgFIAAgIIAfgVIAHAFIAFgKQADgHACABIAHABQACgIAFgEQAJgGAGAAQALAAABAdQAFASABAIQABAMAJAPQAEAUAAAHIAAAJIgPAIQADAIADACIASAFQAHADAJAUQAGAPAAADQAAACgFAHIAIAJQAKAIAAACIAGAMIAHAUQABACABAKQANANABANIABALIAIAOIARAgIgJAGQADAHAEADIAFABIgBAJQAoAlABAkQACAJAPAbQAVApACAGQADAJAGAIIAYA1IgBAMQAYAMAAALQAAAGgMAFQAEAHADABIAIAEQAFACAGAMIAKAcIAWAiQgIAFAAAIIABAFIgTAHIgOABQgGABgWAJQgKgXgBgKgAhSBYQAKAAARAGIAaADQAHAMAMgBIAXgLIANACIAXAAIAIACIAMgBIAKABIAKgBIAKADIAYgEIASgBIAigEIAdADQAHAAAAgFIgEgNIgCgJQgHgGgDgGQgOgcgCAAQgEgGgCgGQgBgIgFgHQACgJAAgHQAAgEgDgJIgOACIgFgLIgDgKIgJgNIgJgQIgEgIQgDgQgHgNQgGgJAAgIIAIgEQgEgGgFAAIgGABIgFgLIgKgOIgCgQIgGgKIgGgOIgNgPIgHgYIgHgLQgEgKgHgJQgJAFgEAHQgHANABALIgDAAIgQAaIgXAqQgGAMgCAHQgHAFgCAGQgHARgOAEIACALIgGAEIAAAAIgNgCIgDAFIAKAHQgEAPgKAPQgSAjgRAKQgEADAAAKQAAAHgEAGIgKAUIgJAJIgFAMIgLATIgFANQAJgEABAAQADAAAGAFIAMgCIAFAJQAIgDAOAAg");
	this.shape_6.setTransform(255.4,257.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#990000").s().p("AgaF5IgHABIgMABIgGAFIgtAAIgLgBIgegCQgHgHgEgCIgOgCIgCAGQgpgLgLgNQgOgOgIgGQgCgKgGgHIgJABQgHAAgEgDQgGgFgQgUIgQgRQAEgNAAgGQAAgLgKAAIgKABQgCgHgIgMIgBgGIgSgwQgFgQgBgKIAAgCIACgIIgEgOIgBgiQAAgIgCgHIAAgIQAAgCADgHIALgDQgCgPgCgJIgKAAIADgfIAEgLIAJglIAHgTIASAAIACgNQgNAAAAgHQAAgIAZgmIAGgLIAQgTIAKgRIAIgHQAHADADAAQACAAAGgDIgCgRIAUgUQANgNAPgLIAKgKIAKgGIAGgHIAhgWQASgPAIgEQAIAHADABQAKgEAAgDQACABABgKIAZgLIAPgIIAXgIIAMgDQAPgBAHgEQAYgGAbgGIAKgCIAKgCIAIgBIAPAAIAOgEIAEgBIAhASQAMgRAEAAIAbABIAjACQAQAEANABIAFAFIACAAQAFgEADAAQAEgBAGAIQgCAEgCACIgLAGQgGAEgGAEQgNAKgFAAQgFAAgSgEIgRgGIgZgCQgPgJgEAAQgBAAAAAAQAAAAgBAAQAAABgBAAQAAAAgBABQgFAEgBAAIgFgCIgSgDIgMgNIgPAQQgEAEgFAAIgNgCIgaAIQgMgFgEAAQgFAAgQAKQgDABgSABQAAAHgDABIgiAMQgJAFgRAKIgUANIgHAJIgNgCIgGAAQgDANgGAFIgLAJQgDACgGACQgCgBgDAGQgCAFgMAKIgKgEIACALIgNAKIgKAOQgJALgIANIgQAaIgJABQgDAHgEAEIgBgBIgEAAIgBAFIAFAAIgBAHIgGAMIgQAmIgFAIIABAVQAAAFgHARQgFAKgCAQQgLACgCAIQANAHAAAFIAAABIgDAdIACASQgLAIAAAIQAAAFAFAGIAIgBQABAJAEAKIACALIgmAJIgCABQgBACAhACIALADQABAXAHAPIAAABIgEAaQAAADAEAAQAEAAAGgEIAIAMQAJANAAAFIAEAOQAAADAIAFQAKAHAIAJQAGAIANALIAGAGIAHAHIAKADQAHACACADIAEAFIADgDQAOAQAVAMIAUAJIAPAGQAJAAAQgUQALALATAAQAGAAAEgCIAJgEIAHACIAEAAIAtgCIAPAAIAQAAIAHABIAVgCQAEgFAEgCIAkgEIAZgFIANAFIACABQAIAAACgOIAOABQAEABAYgGIAUgDIAfgIIgBgEQAAgHAEgBIAhgKIghgTIAggTIghgoIABgCQADgJAAgOIgEgdIgBgqIAAgFQAAgMAHgCIAYgLIABgBIgCgBQgMgGgPgBIgHAAQgCgUgLgIQgEgCgEgBIgJABIgGgDIgKACQgDACglgBIgLgCQgFAEgDgBQgGAAgBgFQAAgGAMgJQAIgGAEgCIAMAAIAQAAIAUAIIADAAQAFAAAJgIQAPAEAHAAIAGgBIALgBIAPACIAagEQAIANAAAEIAAAAIgDAWIAAAGQACAPABANIgBAiIgEAWIgCAPIgJAAQgGAPAAAEIABAMIgKAEIAhAbIgCADIgDAJIgIAEQAFALADABQACABAEAAIAEAKIgBAQIAAACQAAALACAEIAEAHIgDAJIgBAEIABAHIgNACQgEAJgEABIggABQgdAIgGAAQgFAAgLgCIgEAFQgLAAgnAHIgBAAIgFgBIgGgBQgFABgSAHQgFACgZAAIgWAFQgIACgMAAIgfAIIgPABQgkAFgdAEQgGgIgDABgAFJC+IANgFIAEgIQADAAADAFIgKADIgBABQgCACgJAFIgBgDgAFJC+IAAAAg");
	this.shape_7.setTransform(175.25,256.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("EhEqAw6MAAAhhzMCJVAAAMAAABhzg");
	this.shape_8.setTransform(439.475,312.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,879,626);


(lib.clock_2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AA7BGQgDgOAAgNIABgJIABgJIABgJIABgPIACgMIAAgGIABgCIAAgEIABgJIAAgGIAAgBIAAgBIgBgDIgDAFIgGAHIgJANIgEAFIgDAFIgEAFIgGAGIgMASIgBACIgCACIgDAEQgGAJgFABQgKgCgDgGIgBgDIgCgCIgBgCIgBgCIgEgHIgCgFIgFgJIgFgKIgCgGIgBgEIgBgDIgBgEIgCgGIgCgGIgCgGIgCAHIgCAJIgDAJIgCAJIgCAHIgBAGIgFATQgDAIAAAIIABAEIABAHIABAHIAAAGQAAACgDAEQgCAEgDAAIgCgBIgDAAQgGAAgCgGQgDgHAAgHIABgFIACgFIABgGIACgGIAAgCIAEgPIADgMIADgJIADgMIAEgMIACgJIABgIIABgFIACgFQADgFADAAIALABQAFACACAFIADAEIABAFIACAGIABAGIACAEIABAFQAIAXAPAVIACgCIACgCIACgBIADgEIACgFIAGgIIAGgIIADgEIAFgGIAFgGIADgFIAEgDIACgEIADgEIAEgEIACgEIACgCIABgCIAEgFIAFgHIAEgHIAEgFIACgBIADABIAFACIADADQABAAAAAAQAAABAAAAQABAAAAABQAAAAgBAAIAAACIgBACIgCACIAAACIAAABIgBABIAAADIgBABIgBAHIgBAHIAAAPIgBAIIgBAIIgBAJIgBAHIgBAOIAAAPIAAAOIAAATIAEADIAEADIABADQAAAEgEAEQgEADgDAAQgKAAgEgNg");
	this.shape.setTransform(91.3563,28.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AhLBKQgEgDAAgEQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABgBIAGgBIAEgFIAHgIIAIgLIAKgNIAEgHIAEgFIACgEIAEgGIADgDIADgEIADgEIADgDIADgFIAEgFIADgFIAGgJIAGgOQAMgcAFAAIAFABQAAAAABAAQAAAAAAAAQAAABABAAQAAAAAAABIABACIAAAEIAAADIAAACIAAAEIAAAGIAJAWIAFANIAFAQIAGANIADAJIADAJIAFALIAHALQAHAJAAADQAAAEgDADQgCACgEABIgEgBIgCgDIgEgFIgGgLIgGgLIgBgDIgBgCIAAgCIgCgEIgEgLIgDACIgCABIgEABIgDAAIgCAAIgDABIgDABIgDABIgKACIgKACIgLADIgMACQgDAAgDADIgKAPQgIALgFAFQgGAGgFgBQgGAAgFgCgAAKgZIgKAOIgIANIgJAQIACAAIAEAAIAFAAIAEgBIADgBIAEgBIADgBIAEgBIADgBIAMgCIAKgDIgEgLIgEgMIgFgMIgEgLIgKAOg");
	this.shape_1.setTransform(73,29.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgwBAQgIgCgHgGIgCgBIgDgCIgBgBIgBgDQAAgKAMAAQACAAAEADIACACIACABQAKAFALAAQAKgBALgEQAKgEAIgHIAFgFIABgFQAAgHgDgFQgEgEgGgDQgFgDgGgBIgOgBIgEAAIgFAAIgGgBIgDAAQgFgBgFgEQgGgDAAgDQAAgEAEgEIAIgNIANgSQAGgGACAAIAFgBIAIgBIANAAIAQgBIAJAAIAIgBIAEgBIAGgBIAJgCQAGAAAFADIABABIABABIABABIAAABQgBADgDAEQgEAFgDAAQgHABgOAAIgEAAIgJAAIgKAAIgJAAQgNAAgJACIgDAEIgDAEIgDADIgDAGIgEAFIgCADIAGACIAKACIAGABIAEABIAGABIABAAQASADAJAIQAJAFAAARIgBAIIgGAIIgGAIIgHAGQgMAHgKAEQgLADgNAAQgKAAgIgCg");
	this.shape_2.setTransform(58.55,29.75);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgwBAQgIgCgHgGIgDgBIgCgCIgBgBIgBgDQAAgKAMAAQACAAAEADIACACIACABQAKAFALAAQAKgBALgEQAKgEAIgHIAFgFIABgFQAAgHgEgFQgDgEgGgDQgFgDgGgBIgOgBIgEAAIgFAAIgFgBIgFAAQgEgBgGgEQgFgDAAgDQAAgEAEgEIAIgNIANgSQAFgGADAAIAFgBIAIgBIAMAAIARgBIAJAAIAIgBIAEgBIAGgBIAJgCQAGAAAEADIACABIABABIABABIAAABQAAADgEAEQgDAFgEAAQgIABgNAAIgEAAIgJAAIgKAAIgJAAQgNAAgJACIgDAEIgDAEIgDADIgDAGIgEAFIgCADIAHACIAJACIAFABIAGABIAFABIACAAQARADAJAIQAJAFAAARIgBAIIgGAIIgGAIIgHAGQgMAHgKAEQgLADgNAAQgKAAgIgCg");
	this.shape_3.setTransform(43.95,29.75);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgHALIgCgCIgBgDIAAgGIAAgHQAAgEAMAAIADAAQADAAACADQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAIgBAGQAAACgFAFQgGAEgBAAIgFgBg");
	this.shape_4.setTransform(33,34.675);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhEBBQAAgIAEgFQAFgHAIgFIAJgGIALgFIAKgGIAIgGIAIgGIAGgHQAIgGAEgHIAJgMQADgGAAgGQAAgFgEgFQgEgEgFgEQgGgDgEgBQgFAAgKAHIgJAGIgHAFIgCACIgCADIgCACIgDABIgDABIgEAAQgCAAgCgEIgCgHIABgDIAFgEIAGgEIAJgHIAIgFIAIgEIAHgCQAGgCALAAQAJAAAJAHQAJAJAFAKIAEAIQAAAHgHALIgHAKIgIAKIgQAQQgNAMgMAGIAHAAIAJAAIAdABIAGABIAGAAIAKAAIAHgCIAGgBQAAAAABAAQAAAAAAABQABAAAAAAQABABAAABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIgBAFQgCADgGACQgGADgEAAIgDAAIgOgBQgOgEgTAAIgIAAIgJABQgJACgGACQgMAEgDAEIgGAGQgCACgFAAQgIAAAAgGg");
	this.shape_5.setTransform(23.025,30.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#333333").ss(20,1,1).p("Ao+lTIR9AAIAAKnIx9AAg");
	this.shape_6.setTransform(57.475,34);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#666666").s().p("Ao+FUIAAqnIR9AAIAAKng");
	this.shape_7.setTransform(57.475,34);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-10,135,88);


(lib.clock = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AApBaIgIhyIgBAAIgZByIgOAAIgXhyIAAAAIgKByIgXAAIARizIAWAAIAYB9IAAAAIAah9IAVAAIARCzg");
	this.shape.setTransform(71.9,22.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAaBaIgHgjIglAAIgHAjIgXAAIAnizIATAAIAnCzgAgPAkIAfAAIgQhUIAAAAg");
	this.shape_1.setTransform(58.475,22.125);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpBbIAgg+IACgFIACgFQALgXAFgPQAGgPAAgOQAAgKgEgFQgEgGgHAAQgKAAgDAKQgCAKgBATIgXAAQgBgmALgLQALgLATAAQAnAAAAAoQAAAOgFARQgGARgMAZIgVAvIAmAAIAAAVg");
	this.shape_2.setTransform(46.85,22);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDBaIAAigIgQAAIAAgTIAnAAIAACzg");
	this.shape_3.setTransform(35.725,22.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#333333").ss(15,1,1).p("AoqkDIRVAAIAAIHIxVAAg");
	this.shape_4.setTransform(55.475,26);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#666666").s().p("AoqEEIAAoHIRVAAIAAIHg");
	this.shape_5.setTransform(55.475,26);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-7.5,-7.5,126,67);


(lib.cam_buttons = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAbApIAAg6QAAgMgJAAQgKAAAAAOIAAA4IgOAAIAAg7QAAgFgDgDQgCgDgEAAQgKAAAAANIAAA5IgQAAIAAhQIAQAAIAAAHQAHgIAKAAQAKAAAEAKQAIgKALAAQARAAAAAUIAAA9g");
	this.shape.setTransform(315.875,113.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgSAjQgHgIABgaQAAgVAEgKQAEgLALAAQAFAAADADQADACAEAGIAAAAIAAgJIAQAAIAABQIgQAAIAAgKIAAAAQgHALgIAAQgHAAgGgHgAgGgWQgCAFAAAPQAAAQACAHQABAIAGAAQAFAAACgHQACgHAAgQQAAgPgBgGQgCgGgGAAQgEAAgDAGg");
	this.shape_1.setTransform(307.1,113.625);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgMAgQgGgLAAgVQAAgXAHgJQAIgJAIAAQAGAAAIADIAAANQgGgCgDAAQgGAAgDAHQgCAHgBAOQAAAcAMAAQADAAAGgDIAAAMQgIAEgGAAQgMAAgFgKg");
	this.shape_2.setTransform(301.25,113.625);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgaA8IAUgpIACgDIABgEQAIgOADgLQADgJAAgJQAAgGgCgEQgDgEgEAAQgHAAgCAHQgBAGAAANIgQAAQgBgZAIgHQAGgIANAAQAaAAAAAbQAAAJgDALQgEALgJAQIgNAfIAZAAIAAAOg");
	this.shape_3.setTransform(291.45,111.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAbApIAAg6QAAgMgJAAQgKAAAAAOIAAA4IgOAAIAAg7QAAgFgDgDQgCgDgEAAQgKAAAAANIAAA5IgQAAIAAhQIAQAAIAAAHQAHgIAKAAQAKAAAEAKQAIgKALAAQARAAAAAUIAAA9g");
	this.shape_4.setTransform(446.875,22.575);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgTAjQgFgIgBgaQAAgVAFgKQAFgLALAAQAEAAADADQADACADAGIABAAIAAgJIAPAAIAABQIgPAAIAAgKIgBAAQgGALgHAAQgIAAgHgHgAgGgWQgCAFAAAPQAAAQABAHQADAIAEAAQAGAAACgHQACgHAAgQQAAgPgCgGQgCgGgFAAQgFAAgCAGg");
	this.shape_5.setTransform(438.1,22.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgMAgQgGgLAAgVQAAgXAIgJQAHgJAJAAQAFAAAHADIAAANQgFgCgDAAQgGAAgEAHQgCAHAAAOQAAAcALAAQAEAAAGgDIAAAMQgIAEgGAAQgLAAgGgKg");
	this.shape_6.setTransform(432.25,22.625);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgCA7IAAhoIgKAAIAAgNIAZAAIAAB1g");
	this.shape_7.setTransform(422.125,20.775);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#000000").ss(1,1,1).p("AlYClIE7lJIF2FJ");
	this.shape_8.setTransform(109.5,212.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f().s("#333333").ss(33,1,1).p("AwoikIQoAAIQpAAIAAFJIqyAAIqxAAIruAAg");
	this.shape_9.setTransform(106.5,212.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("#333333").ss(25,1,1).p("AnBC5ILtAAAHCmUIAAMp");
	this.shape_10.setTransform(402,97.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#333333").ss(10,1,1).p("AFjq7IKyAAIAAHWIqyAAgAwUDIIK8AAIAAH0Iq8AAg");
	this.shape_11.setTransform(378.5,70);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AF3ClIl3lJIk6FJIruAAIAAlJIQoAAIQpAAIAAFJgAk6ClIE6lJIF3FJg");
	this.shape_12.setTransform(106.5,212.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#666666").s().p("AwUK8IAAn0IK8AAIAAH0gAFjjlIAAnWIKyAAIAAHWg");
	this.shape_13.setTransform(378.5,70);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16.5,-5,504.5,250.5);


(lib.Buttontoplay = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFCLQAAgJAJgKQALgLALAAQAUAAAAAOQAAAGgFAIQgFAJgIAHQgHAGgHAAQgTAAAAgUgAgIBCQgKgYAAgOQAAgNAIgOQAGgKAKgKIAagXIASgQQAPgOAIgMQAIgLAAgNQAAgYgdAAQgTAAgaAJQgZAJgWANQgXANgKAKIgKAIQgFAEgDAAQgGAAgGgFQgHgFAAgHQAAgDADgCIAGgFIAIgFQAhgWApgTQAogTAiAAQAaAAAPAMQAPAMAAAVQAAARgLARQgMAQgUARIgOANIgQAOQgNALgIALQgIALAAAOQAAALAFAPIADAGIACAGQAAAGgEAEQgEADgFAAQgIAAgGgNg");
	this.shape.setTransform(180.475,63.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAJCjQAAgMAMhAQANhAAIgiQgMANgJAIQgKAHgNAAQgUAAgUgfQgVgggUgsIgFgKQgHgOgHgLQgHgLAAgBQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBQAEgBAFAAQAQAAANAfQASAsASAfQASAfASAAQAMAAAKgJQAJgIAGgLQAGgLAHgTIAMghQAQgwACgHIAEgPQACgEAFAAQAFAAAFADQAFAEAAAFQAAAJgDAJIgKAcIgOAmQgWBAgLBNIgDAcIgCAaQAAAGAEAFIAEAHQAAADgHAIQgGAIgIAGQgIAHgFAAQgKAAAAgIg");
	this.shape_1.setTransform(155.625,62.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah4C6QgEgDAAgFQAAgGAGgSIAHgVIAIgXIARgvIAOglIgmAKQgUAFgEAAQgGAAgDgFQgCgEAAgFQAAgGADgCQADgCAHgCIAogJIAdgGIAIgYIAFgQIAHgYIAIgaIAWhMIAEgLQADgEAEAAQAJAAAIADIADgFQACgDADgBQADgBAFAAQAIAAAMAUQAMAVALAcQAGAQAKAhIAOArIAMgCIAHgDIAFgDIAGgEQACgBAEABQAGADAAAKIgCAHQgCAEgCACQgEADgLADIgPACIAEASQAEAMAEAWQAJAzAJAjIADAOQgBAFgDADQgFAEgFAAQgFAAgEgGQgEgFgBgEIgJgmIgIgyIgHggIgGgZIhlAPIgdAFIgKAeIgOAoQgRA2gIAeQgBAHgFAEQgEAFgHAAQgFAAgEgDgAANidQgKATgEAQIglB3IA5gKIAwgIIANgCIgKglQgIgdgHgSQgHgTgLgTQgLgUgIgFg");
	this.shape_2.setTransform(127.5,65.675);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhjCbQgDgFAAgEQAAgDACgCIAFgDIAEgBIAAh+QAAhIgFgoIgGgrQAAgIAFgDQAFgFAGAAQADAAACAEQACACABAGQAFARADAtQADAuAAAwIgBBPIAAAwIAZgBIAmgDQAcgEAkgHQAegGAGABQAFAAACAEQABAGAAAHQAAAGgGAEQgFAEgIAAIhVAHIg8AFIgfADQgEAAgDgGg");
	this.shape_3.setTransform(100.725,61.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgYCQIgBgJQgBgIAAgOQAAgngDhYIgBhAIAAgeIABgTQggAJgXAJIgVALIgMAHQgFADgEAAQgEAAgDgEQgCgDAAgFQAAgHASgJQATgKAbgJQAcgJAXgFQAagFAhAAQAtAAAaAMQAaAMAAAXQAAAegXAVQgZAVgrATIgfANIgUAHQADA9AAArQAAAOADAJQACAIAAADQAAAFgEAEQgGAEgGAAQgIAAgCgLgAgHiDIgCATIAAAbIAAAlIABAeQAJgBAigOQAhgOAXgSQAWgSABgUQgBgRgVgHQgWgHgfAAQgXAAgXADg");
	this.shape_4.setTransform(68.9,65.125);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AuJHUQl3jCAAkSQAAkRF3jBQF3jCISAAQITAAF2DCQF4DBAAERQAAESl4DCQl2DBoTAAQoSAAl3jBg");
	this.shape_5.setTransform(128.1,66.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,256.2,132.2);


(lib._699AM = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABABkIAAiOQAAgdgWAAQgYAAAAAiIAACJIgjAAIAAiRQAAgLgGgHQgHgIgJAAQgYAAAAAfIAACMIglAAIAAjEIAlAAIAAASQASgVAXAAQAZAAAMAZQASgYAaAAQAqAAAAAvIAACXg");
	this.shape.setTransform(127.25,48.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AApCPIgLg5Ig7AAIgLA5IglAAIA+kdIAfAAIA+EdgAgYA6IAxAAIgZiHIAAAAg");
	this.shape_1.setTransform(105.025,44);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgnCRIAHgOQAlhPAHgTQgOAFgKAAQgXAAgOgSQgOgSAAgwQAAglAGgTQAFgUAPgLQAOgLAYAAQAhAAAPAUQAPAVAAA8QAAApgIAbQgJAegUAoIgZAygAgShjQgFALAAAYQAAAmAEAPQAEAOAPABQARAAAEgNQADgNAAgfIAAgFQAAg0gYAAIAAAAQgMgBgGAMg");
	this.shape_2.setTransform(86.925,43.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgnCRIAHgOQAlhPAHgTQgOAFgKAAQgXAAgOgSQgOgSAAgwQAAglAGgTQAFgUAPgLQAOgLAYAAQAhAAAPAUQAPAVAAA8QAAApgIAbQgJAegUAoIgZAygAgShjQgFALAAAYQAAAmAEAPQAEAOAPABQARAAAEgNQADgNAAgfIAAgFQAAg0gYAAIAAAAQgMgBgGAMg");
	this.shape_3.setTransform(70.125,43.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPBGQgGgHAAgJQAAgKAGgHQAHgHAIAAIABAAQAJAAAGAHQAHAGAAAKQAAAJgHAHQgGAHgJAAQgJAAgHgGgAgPgkQgHgGAAgKQAAgKAHgGQAGgHAJAAIAAAAQAKAAAGAHQAHAGAAAKQAAAKgHAHQgGAGgKAAQgJAAgGgHg");
	this.shape_4.setTransform(57.475,50.875);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgxB7QgOgWAAgwQAAgfADgVQADgTAIgXQAIgVANgcIAbg2IAqAAIgjBGIgSAqQAMgGAKAAQAZAAAOASQAPASAAAzQAAA2gQAVQgQAVgiAAQggAAgPgWgAgRAHQgGAKAAAZIABAEIAAAIQAAAfAFANQAFANANAAQAXABAAgwIgBgDIAAgFIABgKIAAgEQAAgdgHgIQgHgIgJABQgNAAgFAJg");
	this.shape_5.setTransform(44.725,44.15);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("#000000").ss(0.1,1,1).p("AjqB4IEDjvIDSDR");
	this.shape_6.setTransform(388.45,557.95);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f().s("#333333").ss(20,1,1).p("AtMmoIaZAAIAANRI6ZAAg");
	this.shape_7.setTransform(84.475,42.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#666666").s().p("EAEnAuGIAAomMAjUAAAIAAImgEARHAq+IEEjwIDSDSIjSjSgEgn6ggzIAAtSIaaAAIAANSg");
	this.shape_8.setTransform(255.475,294.975);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-10,-10,521,600);


// stage content:
(lib.Lim_Wei_Jun_project = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,8,210];
	// timeline functions:
	this.frame_0 = function() {
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.button_4.addEventListener("click", fl_ClickToGoToWebPage_3);
		
		function fl_ClickToGoToWebPage_3() {
			window.open("https://freddy-fazbears-pizza.fandom.com/wiki/Five_Nights_at_Freddy%27s_Wiki", "_blank");
		}
		
		
		
		
		
		
		/* Click to Go to Frame and Play
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and continues playback from that frame.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		this.button_2.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_10.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_10()
		{
			this.gotoAndPlay(11);
		}
	}
	this.frame_8 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
	}
	this.frame_210 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
		
		/* Click to Go to Frame and Stop
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and stops the movie.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		
		this.button_7.addEventListener("click", fl_ClickToGoToAndStopAtFrame_27.bind(this));
		
		function fl_ClickToGoToAndStopAtFrame_27()
		{
			this.gotoAndStop(1);
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(8).call(this.frame_8).wait(202).call(this.frame_210).wait(10));

	// REplay__
	this.button_7 = new lib.replay();
	this.button_7.name = "button_7";
	this.button_7.setTransform(413,426.5,1,1,0,0,0,117,40.5);
	this.button_7._off = true;
	new cjs.ButtonHelper(this.button_7, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get(this.button_7).wait(210).to({_off:false},0).wait(10));

	// gameover
	this.instance = new lib.gameover("synched",0);
	this.instance.setTransform(401.5,294.95,1.2024,1,0,0,0,439.4,312.9);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(210).to({_off:false},0).wait(10));

	// jumpscare
	this.instance_1 = new lib.willy_jumpscare();
	this.instance_1.setTransform(-65,-32,0.4583,0.6279);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(185).to({_off:false},0).wait(13).to({scaleX:0.6958,scaleY:0.7352,x:-255,y:-79},0).to({_off:true},12).wait(10));

	// mouse_2
	this.instance_2 = new lib.mouse_2("synched",0);
	this.instance_2.setTransform(737,56.1,1,1,0,0,0,33,20.1);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(62).to({_off:false},0).to({regX:23,regY:31.1,x:633,y:211.1},7).to({x:423,y:269.1},5).to({x:330,y:300.1},5).to({y:250.1},3).to({y:292.1},3).to({x:434,y:454.05},5).to({x:522.75,y:483.3},7).to({x:587.75,y:499.3},7).to({x:411.75,y:428.3},7).to({x:347.75,y:226.35},8).to({x:360.75,y:128.35},5).to({x:402.75,y:174.35},3).to({x:465.75,y:147.35},2).to({x:536.75,y:180.35},2).to({x:568.75,y:117.35},2).to({x:620.75,y:182.35},2).to({x:675.75,y:146.35},2).to({x:746.75,y:180.35},2).to({x:773.1,y:126.35},2).to({x:727,y:400.3},8).to({x:656.8,y:243.6},4).to({x:379.35,y:174.25},4).to({x:261.05,y:335.8},4).to({x:319.8,y:418.25},3).to({x:320.65,y:583},5).to({x:97.65,y:357},4).to({x:362.65,y:46.05},6).to({x:723.65,y:366},5).to({_off:true},1).wait(35));

	// clock5
	this.instance_3 = new lib._699AM("synched",0);
	this.instance_3.setTransform(274.55,309.95,1,1,0,0,0,250.5,289.9);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(170).to({_off:false},0).to({_off:true},15).wait(35));

	// willy_office
	this.instance_4 = new lib.willy_at_office();
	this.instance_4.setTransform(-106,-42,0.5437,0.6186);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(170).to({_off:false},0).to({_off:true},15).wait(35));

	// cam_buttons_mouse_outcambutton
	this.instance_5 = new lib.cam_buttons("synched",0);
	this.instance_5.setTransform(522.8,483.2,1,1,0,0,0,235.8,120.2);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(62).to({_off:false},0).to({_off:true},108).wait(50));

	// Clock_4
	this.instance_6 = new lib.time_659am("synched",0);
	this.instance_6.setTransform(82,64.1,1,1,0,0,0,61.8,36.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(150).to({_off:false},0).to({_off:true},20).wait(50));

	// willy_stage_gone_not_sigma
	this.instance_7 = new lib.stage_willy_gone();
	this.instance_7.setTransform(-123,-7,0.5537,0.6297);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(150).to({_off:false},0).to({_off:true},20).wait(50));

	// clock_3
	this.instance_8 = new lib.time469("synched",0);
	this.instance_8.setTransform(88.95,62.4,1,1,0,0,0,60.4,33);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(105).to({_off:false},0).to({_off:true},45).wait(70));

	// clock_2
	this.instance_9 = new lib.clock_2("synched",0);
	this.instance_9.setTransform(80.55,62.05,1,1,0,0,0,57.5,34);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(62).to({_off:false},0).to({_off:true},43).wait(115));

	// outside_office
	this.instance_10 = new lib.outside_office();
	this.instance_10.setTransform(-20,-27,0.4355,0.5963);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(105).to({_off:false},0).to({_off:true},45).wait(70));

	// willy_stage
	this.instance_11 = new lib.willy_stage();
	this.instance_11.setTransform(-64,-27,0.4917,0.6093);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(62).to({_off:false},0).to({_off:true},43).wait(115));

	// clock
	this.instance_12 = new lib.clock("synched",0);
	this.instance_12.setTransform(72.55,46.05,1,1,0,0,0,55.5,26);
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(30).to({_off:false},0).to({_off:true},32).wait(158));

	// mouse
	this.instance_13 = new lib.Tween9("synched",0);
	this.instance_13.setTransform(749,40.1);
	this.instance_13._off = true;

	this.instance_14 = new lib.Tween10("synched",0);
	this.instance_14.setTransform(728,271.1);
	this.instance_14._off = true;

	this.instance_15 = new lib.Tween11("synched",0);
	this.instance_15.setTransform(622,532.1);
	this.instance_15._off = true;

	this.instance_16 = new lib.Tween12("synched",0);
	this.instance_16.setTransform(514,585.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_13}]},30).to({state:[{t:this.instance_14}]},9).to({state:[{t:this.instance_15}]},10).to({state:[{t:this.instance_16}]},10).to({state:[]},3).wait(158));
	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(30).to({_off:false},0).to({_off:true,x:728,y:271.1},9).wait(181));
	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(30).to({_off:false},9).to({_off:true,x:622,y:532.1},10).wait(171));
	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(39).to({_off:false},10).to({_off:true,x:514,y:585.1},10).wait(161));

	// cam_button
	this.instance_17 = new lib.Symbol1();
	this.instance_17.setTransform(417.05,586.8,1,1,0,0,0,130,28);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(30).to({_off:false},0).wait(29).to({scaleX:1.0615},0).to({_off:true},3).wait(158));

	// Office
	this.instance_18 = new lib.office();
	this.instance_18.setTransform(-227,-87,0.6627,0.6674);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(30).to({_off:false},0).to({_off:true},32).wait(158));

	// Help_
	this.button_4 = new lib.help();
	this.button_4.name = "button_4";
	this.button_4.setTransform(695.5,81.55,1,1,0,0,0,93.5,45.5);
	new cjs.ButtonHelper(this.button_4, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.button_4).to({_off:true},10).wait(210));

	// button
	this.button_2 = new lib.Buttontoplay();
	this.button_2.name = "button_2";
	this.button_2.setTransform(646.25,518.9,1,1,0,0,0,128.1,66.1);
	new cjs.ButtonHelper(this.button_2, 0, 1, 2);

	this.timeline.addTween(cjs.Tween.get(this.button_2).to({_off:true},10).wait(210));

	// time
	this.instance_19 = new lib.TIME("synched",0);
	this.instance_19.setTransform(430.05,297.5,1,1,0,0,0,450.4,310.8);
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(9).to({_off:false},0).to({_off:true},21).wait(190));

	// background
	this.instance_20 = new lib.HELPWANTEDwillypaperbackground();
	this.instance_20.setTransform(-83,-18,0.5392,0.5007);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AiNGPQjRiPAAjLQAAgcAEgaQkBgQjGg6QkThQAAhyQAAhxEThQQEShQGFAAQGEAAETBQQCeAuBDA5QA+AcA4AmQDRCQAADKQAADLjRCPQjRCQkoAAQkoAAjQiQg");
	this.shape.setTransform(644.6,507.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.instance_20}]}).to({state:[{t:this.shape},{t:this.instance_20}]},9).to({state:[]},1).wait(210));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(145,213,935.9000000000001,502.1);
// library properties:
lib.properties = {
	id: '1707B41E3B924C47B9DAA523543898BC',
	width: 800,
	height: 600,
	fps: 25,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/Lim_Wei_Jun_project_atlas_1.png", id:"Lim_Wei_Jun_project_atlas_1"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['1707B41E3B924C47B9DAA523543898BC'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;