(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"project_edlyna_atlas_1", frames: [[3026,0,405,720],[0,4034,1125,750],[1127,4034,500,750],[1629,4034,500,750],[2131,4034,500,750],[2633,4034,500,750],[0,0,3024,4032]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.Bitmap3 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap4 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap6 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap7 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap8 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap9 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.pexelsjulieaagaard2467287 = function() {
	this.initialize(ss["project_edlyna_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.website_button = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape.setTransform(72.575,26.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgDA6QgFgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAFgCAGgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAADgCQADgCACgEIAEAAQgEAKgGAEQgGAFgGAAQgFAAgDgCg");
	this.shape_1.setTransform(65.4,24.775);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgUBGIAAgEQAHAAACgCQACAAABgDQACgEAAgIIAAgiQAAgPgBgDQAAgBgBAAQAAgBAAgBQAAAAgBgBQAAAAAAAAIgEgBIgHABIgBgDIAagMIAEAAIAABHQAAAIABAEQABADADAAQACACAGAAIAAAEgAgFg0QgDgCAAgFQAAgDADgEQADgDADAAQAEAAADADQADAEAAADQAAAFgDACQgDADgEAAQgDAAgDgDg");
	this.shape_2.setTransform(59.775,23.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRAtIgGgBQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAAAIgEAAIAAggIAEAAQACAOAJAHQAHAHAJAAQAHAAAEgEQAEgEAAgGQAAgGgFgFQgFgFgNgHQgOgGgEgFQgFgGAAgIQAAgLAIgIQAHgHAMAAQAFAAAHACIAHABIADAAIACgDIACAAIAAAeIgCAAQgEgOgGgFQgGgGgIAAQgHAAgEAEQgEAEAAAEQAAAGADADQADAEAJAFIAOAHQATAJAAAPQABANgKAHQgJAHgLAAQgIAAgKgCg");
	this.shape_3.setTransform(53.2,26.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgOBEQgIgDgJgFIAAhcIAAgTIgDgFIgEgBIgGACIgCgEIAbgLIAFAAIAABBQANgSAOAAQANAAALAMQAKALAAAUQAAAYgQAOQgOANgQAAQgHAAgIgDgAgFgGIgJAGIAAA2QAEAFAGACQAEADAGAAQAJAAAHgKQAIgKAAgSQAAgSgIgIQgHgJgKAAQgFAAgFADg");
	this.shape_4.setTransform(43.775,23.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_5.setTransform(34.775,26.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAfBEIgehUIgdBUIgEAAIgnhtIgGgPQgCgDgDgCQgDgCgGAAIAAgEIAxAAIAAAEIgCAAQgGAAgCACQgDADAAADQAAADAEANIAaBJIAWg+IgEgLIgDgJIgEgJIgDgDIgFgCIgGgBIAAgEIAyAAIAAAEIgDAAQgGAAgCACQgDADAAAEQAAAFAFAMIAZBHIAZhIQAFgMAAgFQAAAAAAgBQAAgBgBAAQAAgBAAAAQAAAAgBgBIgDgDQgEgBgGAAIAAgEIAnAAIAAAEQgFAAgDACQgDACgDAFIgGAQIglBqg");
	this.shape_6.setTransform(22.425,24.175);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC3366").s().p("AnVDwIAAnfIOrAAIAAHfg");
	this.shape_7.setTransform(46.975,24);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,94,48);


(lib.Tween17 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape.setTransform(277.625,-150.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAABgBQAAAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_1.setTransform(268.225,-153.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_2.setTransform(258.975,-150.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAACgCQADgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgDgCgFAAQgFAAgEADQgFADgIAGIAAAwQAAAJACABQABADACACQADABAHAAIAAADIgtAAIAAgDQAGAAAEgCQABAAAAgBQAAAAABAAQAAgBAAAAQABgBAAgBQACgDAAgHIAAhQQAAgQgBgDQgBgEgCgCIgDgBIgIACIgBgDIAbgLIAEAAIAABBQAMgMAFgDQAGgDAHAAQAHAAAFADQAGAFACAJQACAFAAAQIAAAhQAAAIACADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQADABAGAAIAAADg");
	this.shape_3.setTransform(249.2,-153.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBACgBAEIgDAAIAAgtIADAAQADAOAEAHQAEAHAJAFQAIAFAKAAQANAAAGgHQAIgGgBgJQABgFgDgFQgDgFgFgEQgEgDgQgKQgRgIgHgGQgIgFgDgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQACgCABgEIADAAIAAAuIgDAAQgCgOgFgHQgFgIgHgFQgJgEgIAAQgKAAgHAGQgGAGgBAIQAAAGAFAFQAGAHAWAMQASAKAHAFQAGAFAFAHQADAIAAAHQAAAQgLAKQgNALgRAAIgLgBg");
	this.shape_4.setTransform(238.75,-152.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_5.setTransform(223.725,-150.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAGgFAEgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAAEgCQADgCABgEIAEAAQgEAKgGAEQgGAFgHAAQgEAAgEgCg");
	this.shape_6.setTransform(216.55,-152.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_7.setTransform(209.525,-150.65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_8.setTransform(202.075,-153.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_9.setTransform(194.175,-150.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaAjQgKgNgBgWQAAgUANgNQANgNAQAAQANAAAIAHQAJAHAAAHQAAAEgCACQgDACgEAAQgGAAgDgDQgBgCAAgGQgBgGgDgDQgEgDgGAAQgJAAgGAHQgIAKAAAQQAAAPAIAMQAIAMAMAAQAKAAAHgGQAGgFAFgMIACACQgDARgKAKQgLAJgNAAQgOAAgMgMg");
	this.shape_10.setTransform(184.75,-150.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_11.setTransform(175.275,-150.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgDgCgFAAQgFAAgEADQgFADgIAGIAAAwQAAAJABABQACADADACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDAAgHIAAhQQAAgQgBgDQAAgEgCgCIgDgBIgHACIgBgDIAagLIAEAAIAABBQAMgMAFgDQAGgDAHAAQAHAAAFADQAGAFADAJQABAFAAAQIAAAhQABAIABADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQACABAHAAIAAADg");
	this.shape_12.setTransform(165.3,-153.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgtAtQgOgSAAgZQAAgTAJgQQAJgRAQgJQAPgJASAAQAOAAAOAHIAGACQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQACgDABgEIAEAAIADAtIgDAAQgGgUgMgJQgLgJgQAAQgMAAgKAHQgLAGgGAPQgGAPAAAUQAAASAGANQAFAOAMAHQALAHAOAAQANAAAKgGQAKgFAMgRIADACQgKASgOAIQgNAIgSAAQggAAgSgYg");
	this.shape_13.setTransform(153.625,-152.775);

	this.instance = new lib.Bitmap9();
	this.instance.setTransform(155.95,-88,0.2456,0.2933);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_14.setTransform(116.175,-150.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAABgBQAAAAAAgBQAAAAABgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_15.setTransform(106.775,-153.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_16.setTransform(97.525,-150.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAACgCQADgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgGADgGAGIAAAwQAAAJABABQABADACACQADABAHAAIAAADIgtAAIAAgDQAHAAADgCQABAAAAgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDABgHIAAhQQAAgQgBgDQgBgEgCgCIgEgBIgHACIgBgDIAbgLIAFAAIAABBQAKgMAGgDQAGgDAHAAQAHAAAFADQAGAFACAJQACAFAAAQIAAAhQAAAIACADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQADABAGAAIAAADg");
	this.shape_17.setTransform(87.75,-153.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBACgBAEIgDAAIAAgtIADAAQACAOAFAHQAEAHAJAFQAIAFAKAAQAMAAAIgHQAGgGAAgJQAAgFgCgFQgDgFgGgEQgDgDgQgKQgRgIgIgGQgGgFgEgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCACgEIADAAIAAAuIgDAAQgCgOgFgHQgFgIgHgFQgJgEgIAAQgKAAgHAGQgGAGgBAIQAAAGAFAFQAGAHAWAMQASAKAHAFQAHAFAEAHQADAIAAAHQAAAQgMAKQgMALgRAAIgLgBg");
	this.shape_18.setTransform(77.3,-152.775);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_19.setTransform(62.525,-150.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_20.setTransform(55.075,-153.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_21.setTransform(49.525,-153.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAHAAACgBQACgCABgDQACgDAAgHIAAgjQAAgPgBgDQAAgBgBAAQAAgBAAgBQAAAAgBgBQAAAAAAgBIgEgBIgHACIgBgEIAagKIAEAAIAABHQAAAHABADQABADADACQACABAGAAIAAADgAgFgzQgDgEAAgDQAAgFADgDQADgCADAAQAEAAADACQADADAAAFQAAADgDAEQgDADgEAAQgDAAgDgDg");
	this.shape_22.setTransform(43.925,-153.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAFAuIAAgEIABAAQAHAAACgCQADgCABgDIABgJIAAgkQgBgMgDgGQgDgFgIAAQgKAAgLAMIAAAvQAAAJABACQABADACABQACACAIgBIAAAEIgtAAIAAgEIADAAQAGABADgEQACgDAAgKIAAggIAAgUIgCgFIgFgBIgHABIgBgDIAbgLIAFAAIAAATQAPgTANAAQAHAAAGAEQAFADADAIQACAHABALIAAAmQAAAIABAEQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQACACAHgBIAAAEg");
	this.shape_23.setTransform(36.1,-150.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_24.setTransform(26.975,-150.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAABEIgwhxIgGgLQgCgDgEgCQgDgCgGAAIAAgEIA2AAIAAAEQgJABgDACQgDACAAAEQAAAFAEAKIAiBNIAehMQAFgLAAgFQAAgDgCgCQgEgDgGgBIgCAAIAAgEIApAAIAAAEQgHABgDADQgGAFgEAKIguBwg");
	this.shape_25.setTransform(17.15,-152.625);

	this.instance_1 = new lib.Bitmap8();
	this.instance_1.setTransform(7.95,-78,0.264,0.272);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_26.setTransform(-43.525,-150.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADg");
	this.shape_27.setTransform(-52.925,-153.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_28.setTransform(-62.175,-150.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgFADgIAGIAAAwQAAAJABABQABADAEACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDAAgHIAAhQQAAgQgBgDQAAgEgCgCIgDgBIgHACIgBgDIAagLIAEAAIAABBQAMgMAFgDQAGgDAGAAQAIAAAGADQAFAFADAJQABAFAAAQIAAAhQABAIABADQAAABABAAQAAABAAAAQABABAAAAQABAAAAABQACABAGAAIAAADg");
	this.shape_29.setTransform(-71.95,-153.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQANAAAGgHQAIgGAAgJQgBgFgCgFQgDgFgFgEIgUgNQgRgIgHgGQgHgFgFgHQgDgHAAgIQAAgPALgKQALgKARAAQAJAAAMAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCABgEIAEAAIAAAuIgEAAQgBgOgEgHQgGgIgIgFQgIgEgIAAQgKAAgHAGQgGAGAAAIQAAAGADAFQAHAHAVAMQATAKAHAFQAGAFAEAHQAEAIAAAHQAAAQgLAKQgMALgTAAIgKgBg");
	this.shape_30.setTransform(-82.4,-152.775);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_31.setTransform(-98.075,-150.625);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_32.setTransform(-107.425,-150.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_33.setTransform(-115.125,-150.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgtAyQgTgUAAgeQAAgfAWgUQASgRAZAAQAaAAATATQATAUAAAdQAAAdgTAUQgTAUgbAAQgbAAgSgTgAgcgwQgNARAAAfQAAAgAOARQAKANARAAQASAAAMgOQANgPAAgfQAAghgOgRQgLgNgSAAQgRAAgLANg");
	this.shape_34.setTransform(-125.875,-152.775);

	this.instance_2 = new lib.Bitmap7();
	this.instance_2.setTransform(-144.05,-78,0.2784,0.2559);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_35.setTransform(-165.575,-150.625);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_36.setTransform(-174.975,-153.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_37.setTransform(-184.225,-150.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgGADgHAGIAAAwQAAAJABABQABADAEACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQACgDgBgHIAAhQQAAgQgBgDQAAgEgBgCIgFgBIgGACIgBgDIAagLIAEAAIAABBQALgMAGgDQAGgDAGAAQAIAAAGADQAFAFADAJQACAFAAAQIAAAhQgBAIACADQAAABABAAQAAABAAAAQABABAAAAQABAAAAABQADABAFAAIAAADg");
	this.shape_38.setTransform(-194,-153.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHBEIgNgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQAMAAAHgHQAIgGAAgJQgBgFgCgFQgDgFgFgEIgUgNQgRgIgHgGQgHgFgFgHQgDgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQACgCAAgEIAEAAIAAAuIgEAAQgBgOgEgHQgGgIgIgFQgIgEgIAAQgKAAgHAGQgHAGABAIQAAAGADAFQAHAHAVAMQATAKAHAFQAGAFAEAHQAEAIAAAHQAAAQgMAKQgLALgTAAIgJgBg");
	this.shape_39.setTransform(-204.45,-152.775);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgoA/QgDgDAAgFQAAgEACgCQADgDAFAAQADAAAFADIAGABQADAAADgDQADgDAEgJIAGgPIgghDIgEgHIgFgFIgHgDIAAgDIAqAAIAAADIgCAAQgFAAgCACQgCACAAADQAAAEADAHIAVAsIAUgxIABgIIAAgCIgCgCIgHgBIAAgDIAeAAIAAADIgFACIgFAEIgDAIIgkBYQgFANgJAHQgIAGgIAAQgGAAgEgDg");
	this.shape_40.setTransform(-220.1,-148.475);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_41.setTransform(-228.275,-150.75);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_42.setTransform(-234.925,-150.75);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_43.setTransform(-242.775,-150.625);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgOBEQgIgDgJgFIAAhcIAAgTIgDgFIgEgBIgGACIgCgEIAbgLIAFAAIAABBQANgSAOAAQANAAALAMQAKALAAAUQAAAYgQAOQgOANgQAAQgHAAgIgDgAgFgGIgJAGIAAA2QAEAFAGACQAEADAGAAQAJAAAHgKQAIgKAAgSQAAgSgIgIQgHgJgKAAQgFAAgFADg");
	this.shape_44.setTransform(-252.675,-152.975);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAYAuIgWg4IgZA4IgEAAIgchKQgDgHgDgDQgDgCgGgBIAAgEIAmAAIAAAEQgGAAgBACQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIACAIIATAzIAUgqIgGgMQgCgHgEgBQgCgCgGAAIAAgEIAqAAIAAAEQgIAAgCACQgCACAAADIAAAEIAVAzIATgxIACgJIgCgCQgCgCgFAAIAAgEIAcAAIAAAEQgJABgEAKIgeBMg");
	this.shape_45.setTransform(-264.55,-150.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_46.setTransform(-275.875,-150.65);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_47.setTransform(-283.825,-150.75);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQAEAAADgCQADgCABgEIAEAAQgDAKgHAEQgGAFgHAAQgEAAgEgCg");
	this.shape_48.setTransform(-289.95,-152.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQAMAAAHgHQAIgGgBgJQAAgFgCgFQgDgFgFgEQgEgDgQgKQgRgIgHgGQgIgFgDgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCACgEIADAAIAAAuIgDAAQgCgOgEgHQgFgIgJgFQgIgEgIAAQgKAAgHAGQgGAGAAAIQAAAGADAFQAHAHAWAMQASAKAHAFQAGAFAFAHQADAIAAAHQAAAQgLAKQgMALgTAAIgKgBg");
	this.shape_49.setTransform(-298.3,-152.775);

	this.instance_3 = new lib.Bitmap6();
	this.instance_3.setTransform(-296.05,-88,0.272,0.2692);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f().s("#000000").ss(1,1,1).p("ABB8HIADHqIWmAAMAAJAwlAXo8HIACHqIWmAAA2c8HIAGHqIXaAAMAATAwlEguPgUdIX5AAMAAmAwl");
	this.shape_50.setTransform(-10,0.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#CC3366").s().p("AXzcIMgAJgwlIWmAAMAAAAwlgABXcIMgATgwlIWmAAMAAJAwlgA1wcIMgAlgwlI36AAIX6AAMAAlAwlI4fAAMAAAgwlIAAnqIXzAAIXdAAIWoAAIWnAAIAAHqI2mAAIgBnqIABHqI2mAAIgDnqIADHqI3ZAAIXZAAMAATAwlgA2V0dIgHnqgAXq0dg");
	this.shape_51.setTransform(-10,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.instance_3},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.instance_2},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.instance_1},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.instance},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-306.9,-180.9,612.9,361.9);


(lib.Tween16 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape.setTransform(277.625,-150.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAABgBQAAAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_1.setTransform(268.225,-153.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_2.setTransform(258.975,-150.65);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAACgCQADgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgDgCgFAAQgFAAgEADQgFADgIAGIAAAwQAAAJACABQABADACACQADABAHAAIAAADIgtAAIAAgDQAGAAAEgCQABAAAAgBQAAAAABAAQAAgBAAAAQABgBAAgBQACgDAAgHIAAhQQAAgQgBgDQgBgEgCgCIgDgBIgIACIgBgDIAbgLIAEAAIAABBQAMgMAFgDQAGgDAHAAQAHAAAFADQAGAFACAJQACAFAAAQIAAAhQAAAIACADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQADABAGAAIAAADg");
	this.shape_3.setTransform(249.2,-153.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBACgBAEIgDAAIAAgtIADAAQADAOAEAHQAEAHAJAFQAIAFAKAAQANAAAGgHQAIgGgBgJQABgFgDgFQgDgFgFgEQgEgDgQgKQgRgIgHgGQgIgFgDgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQACgCABgEIADAAIAAAuIgDAAQgCgOgFgHQgFgIgHgFQgJgEgIAAQgKAAgHAGQgGAGgBAIQAAAGAFAFQAGAHAWAMQASAKAHAFQAGAFAFAHQADAIAAAHQAAAQgLAKQgNALgRAAIgLgBg");
	this.shape_4.setTransform(238.75,-152.775);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_5.setTransform(223.725,-150.625);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAGgFAEgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAAEgCQADgCABgEIAEAAQgEAKgGAEQgGAFgHAAQgEAAgEgCg");
	this.shape_6.setTransform(216.55,-152.025);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_7.setTransform(209.525,-150.65);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_8.setTransform(202.075,-153.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_9.setTransform(194.175,-150.625);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgaAjQgKgNgBgWQAAgUANgNQANgNAQAAQANAAAIAHQAJAHAAAHQAAAEgCACQgDACgEAAQgGAAgDgDQgBgCAAgGQgBgGgDgDQgEgDgGAAQgJAAgGAHQgIAKAAAQQAAAPAIAMQAIAMAMAAQAKAAAHgGQAGgFAFgMIACACQgDARgKAKQgLAJgNAAQgOAAgMgMg");
	this.shape_10.setTransform(184.75,-150.625);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_11.setTransform(175.275,-150.625);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgDgCgFAAQgFAAgEADQgFADgIAGIAAAwQAAAJABABQACADADACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDAAgHIAAhQQAAgQgBgDQAAgEgCgCIgDgBIgHACIgBgDIAagLIAEAAIAABBQAMgMAFgDQAGgDAHAAQAHAAAFADQAGAFADAJQABAFAAAQIAAAhQABAIABADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQACABAHAAIAAADg");
	this.shape_12.setTransform(165.3,-153.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgtAtQgOgSAAgZQAAgTAJgQQAJgRAQgJQAPgJASAAQAOAAAOAHIAGACQABAAAAAAQABAAABgBQAAAAABAAQAAAAABgBQACgDABgEIAEAAIADAtIgDAAQgGgUgMgJQgLgJgQAAQgMAAgKAHQgLAGgGAPQgGAPAAAUQAAASAGANQAFAOAMAHQALAHAOAAQANAAAKgGQAKgFAMgRIADACQgKASgOAIQgNAIgSAAQggAAgSgYg");
	this.shape_13.setTransform(153.625,-152.775);

	this.instance = new lib.Bitmap9();
	this.instance.setTransform(155.95,-88,0.2456,0.2933);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_14.setTransform(116.175,-150.625);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAABgBQAAAAAAgBQAAAAABgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_15.setTransform(106.775,-153.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_16.setTransform(97.525,-150.65);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAACgCQADgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgGADgGAGIAAAwQAAAJABABQABADACACQADABAHAAIAAADIgtAAIAAgDQAHAAADgCQABAAAAgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDABgHIAAhQQAAgQgBgDQgBgEgCgCIgEgBIgHACIgBgDIAbgLIAFAAIAABBQAKgMAGgDQAGgDAHAAQAHAAAFADQAGAFACAJQACAFAAAQIAAAhQAAAIACADQAAABABAAQAAABAAAAQABABAAAAQAAAAABABQADABAGAAIAAADg");
	this.shape_17.setTransform(87.75,-153.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBACgBAEIgDAAIAAgtIADAAQACAOAFAHQAEAHAJAFQAIAFAKAAQAMAAAIgHQAGgGAAgJQAAgFgCgFQgDgFgGgEQgDgDgQgKQgRgIgIgGQgGgFgEgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCACgEIADAAIAAAuIgDAAQgCgOgFgHQgFgIgHgFQgJgEgIAAQgKAAgHAGQgGAGgBAIQAAAGAFAFQAGAHAWAMQASAKAHAFQAHAFAEAHQADAIAAAHQAAAQgMAKQgMALgRAAIgLgBg");
	this.shape_18.setTransform(77.3,-152.775);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_19.setTransform(62.525,-150.65);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_20.setTransform(55.075,-153.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAGAAACgBQADgCABgDQABgDAAgHIAAhRQAAgPgBgDQAAgEgCgCIgEgBIgGACIgCgDIAagLIAEAAIAAB2QAAAHACADQABADACACQADABAHAAIAAADg");
	this.shape_21.setTransform(49.525,-153.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgUBFIAAgDQAHAAACgBQACgCABgDQACgDAAgHIAAgjQAAgPgBgDQAAgBgBAAQAAgBAAgBQAAAAgBgBQAAAAAAgBIgEgBIgHACIgBgEIAagKIAEAAIAABHQAAAHABADQABADADACQACABAGAAIAAADgAgFgzQgDgEAAgDQAAgFADgDQADgCADAAQAEAAADACQADADAAAFQAAADgDAEQgDADgEAAQgDAAgDgDg");
	this.shape_22.setTransform(43.925,-153.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAFAuIAAgEIABAAQAHAAACgCQADgCABgDIABgJIAAgkQgBgMgDgGQgDgFgIAAQgKAAgLAMIAAAvQAAAJABACQABADACABQACACAIgBIAAAEIgtAAIAAgEIADAAQAGABADgEQACgDAAgKIAAggIAAgUIgCgFIgFgBIgHABIgBgDIAbgLIAFAAIAAATQAPgTANAAQAHAAAGAEQAFADADAIQACAHABALIAAAmQAAAIABAEQAAAAABABQAAAAAAABQABAAAAAAQABABAAAAQACACAHgBIAAAEg");
	this.shape_23.setTransform(36.1,-150.75);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_24.setTransform(26.975,-150.65);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AAABEIgwhxIgGgLQgCgDgEgCQgDgCgGAAIAAgEIA2AAIAAAEQgJABgDACQgDACAAAEQAAAFAEAKIAiBNIAehMQAFgLAAgFQAAgDgCgCQgEgDgGgBIgCAAIAAgEIApAAIAAAEQgHABgDADQgGAFgEAKIguBwg");
	this.shape_25.setTransform(17.15,-152.625);

	this.instance_1 = new lib.Bitmap8();
	this.instance_1.setTransform(7.95,-78,0.264,0.272);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_26.setTransform(-43.525,-150.625);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADg");
	this.shape_27.setTransform(-52.925,-153.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_28.setTransform(-62.175,-150.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgFADgIAGIAAAwQAAAJABABQABADAEACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQABgDAAgHIAAhQQAAgQgBgDQAAgEgCgCIgDgBIgHACIgBgDIAagLIAEAAIAABBQAMgMAFgDQAGgDAGAAQAIAAAGADQAFAFADAJQABAFAAAQIAAAhQABAIABADQAAABABAAQAAABAAAAQABABAAAAQABAAAAABQACABAGAAIAAADg");
	this.shape_29.setTransform(-71.95,-153.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQANAAAGgHQAIgGAAgJQgBgFgCgFQgDgFgFgEIgUgNQgRgIgHgGQgHgFgFgHQgDgHAAgIQAAgPALgKQALgKARAAQAJAAAMAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCABgEIAEAAIAAAuIgEAAQgBgOgEgHQgGgIgIgFQgIgEgIAAQgKAAgHAGQgGAGAAAIQAAAGADAFQAHAHAVAMQATAKAHAFQAGAFAEAHQAEAIAAAHQAAAQgLAKQgMALgTAAIgKgBg");
	this.shape_30.setTransform(-82.4,-152.775);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AggAfQgKgNAAgRQAAgLAGgNQAGgMAKgFQAKgGAKAAQAVAAAMAPQAKANAAARQAAALgFANQgGAMgKAGQgKAGgMAAQgUAAgMgQgAgMglQgFADgEAIQgDAIAAAMQAAASAIAOQAIAPALAAQAKAAAGgIQAGgIAAgTQAAgXgKgOQgHgJgKAAQgFAAgFADg");
	this.shape_31.setTransform(-98.075,-150.625);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_32.setTransform(-107.425,-150.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_33.setTransform(-115.125,-150.75);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgtAyQgTgUAAgeQAAgfAWgUQASgRAZAAQAaAAATATQATAUAAAdQAAAdgTAUQgTAUgbAAQgbAAgSgTgAgcgwQgNARAAAfQAAAgAOARQAKANARAAQASAAAMgOQANgPAAgfQAAghgOgRQgLgNgSAAQgRAAgLANg");
	this.shape_34.setTransform(-125.875,-152.775);

	this.instance_2 = new lib.Bitmap7();
	this.instance_2.setTransform(-144.05,-78,0.2784,0.2559);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_35.setTransform(-165.575,-150.625);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAGBFIAAgDIAGgBIABgDQAAgDgEgEIgbgjIAWgUIAJgJIAAgCQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgCgCgEAAIAAgDIAnAAIAAADQgIABgFACQgFACgHAGIgWAUIAWAdIANAPQAFAFADABIAJABIAAADgAgxBFIAAgDQAHAAAEgBQAAgBABAAQAAAAAAgBQABAAAAgBQABAAAAgBQABgDAAgIIAAhQIAAgTIgDgGIgEgBIgGACIgCgDIAbgLIAEAAIAABYIAAAeQAAAIACADQAAABAAAAQABABAAAAQABABAAAAQABAAAAABQACABAIAAIAAADgAgSAUg");
	this.shape_36.setTransform(-174.975,-153.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_37.setTransform(-184.225,-150.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AAFBFIAAgDIACAAQAGAAADgCQACgCABgDIAAgJIAAghQAAgOgBgEQgCgEgDgDQgEgCgEAAQgFAAgEADQgGADgHAGIAAAwQAAAJABABQABADAEACQACABAHAAIAAADIgsAAIAAgDQAFAAAEgCQAAAAABgBQAAAAABAAQAAgBAAAAQABgBAAgBQACgDgBgHIAAhQQAAgQgBgDQAAgEgBgCIgFgBIgGACIgBgDIAagLIAEAAIAABBQALgMAGgDQAGgDAGAAQAIAAAGADQAFAFADAJQACAFAAAQIAAAhQgBAIACADQAAABABAAQAAABAAAAQABABAAAAQABAAAAABQADABAFAAIAAADg");
	this.shape_38.setTransform(-194,-153.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHBEIgNgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQAMAAAHgHQAIgGAAgJQgBgFgCgFQgDgFgFgEIgUgNQgRgIgHgGQgHgFgFgHQgDgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQACgCAAgEIAEAAIAAAuIgEAAQgBgOgEgHQgGgIgIgFQgIgEgIAAQgKAAgHAGQgHAGABAIQAAAGADAFQAHAHAVAMQATAKAHAFQAGAFAEAHQAEAIAAAHQAAAQgMAKQgLALgTAAIgJgBg");
	this.shape_39.setTransform(-204.45,-152.775);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgoA/QgDgDAAgFQAAgEACgCQADgDAFAAQADAAAFADIAGABQADAAADgDQADgDAEgJIAGgPIgghDIgEgHIgFgFIgHgDIAAgDIAqAAIAAADIgCAAQgFAAgCACQgCACAAADQAAAEADAHIAVAsIAUgxIABgIIAAgCIgCgCIgHgBIAAgDIAeAAIAAADIgFACIgFAEIgDAIIgkBYQgFANgJAHQgIAGgIAAQgGAAgEgDg");
	this.shape_40.setTransform(-220.1,-148.475);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_41.setTransform(-228.275,-150.75);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_42.setTransform(-234.925,-150.75);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_43.setTransform(-242.775,-150.625);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgOBEQgIgDgJgFIAAhcIAAgTIgDgFIgEgBIgGACIgCgEIAbgLIAFAAIAABBQANgSAOAAQANAAALAMQAKALAAAUQAAAYgQAOQgOANgQAAQgHAAgIgDgAgFgGIgJAGIAAA2QAEAFAGACQAEADAGAAQAJAAAHgKQAIgKAAgSQAAgSgIgIQgHgJgKAAQgFAAgFADg");
	this.shape_44.setTransform(-252.675,-152.975);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAYAuIgWg4IgZA4IgEAAIgchKQgDgHgDgDQgDgCgGgBIAAgEIAmAAIAAAEQgGAAgBACQAAAAgBAAQAAABAAAAQAAABAAAAQgBABAAAAIACAIIATAzIAUgqIgGgMQgCgHgEgBQgCgCgGAAIAAgEIAqAAIAAAEQgIAAgCACQgCACAAADIAAAEIAVAzIATgxIACgJIgCgCQgCgCgFAAIAAgEIAcAAIAAAEQgJABgEAKIgeBMg");
	this.shape_45.setTransform(-264.55,-150.5);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AAMArQgDgDAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgHADgFQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAGQAAAEgCADQgCACgEAAQgEAAgCgCQgCgDAAgEQAAgJAIgHQAJgHAQAAQAKAAAIAEQAGADADAHQABADAAAOIAAAdIABAQIABADIADABIADAAIAIgHIAAAFQgLAPgKAAQgFAAgDgEgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAFAGAAQAHAAALgKIAAghIgSAHg");
	this.shape_46.setTransform(-275.875,-150.65);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgEIABgJIAAgiQAAgPgBgEQAAAAgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAADgCADQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_47.setTransform(-283.825,-150.75);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQAEAAADgCQADgCABgEIAEAAQgDAKgHAEQgGAFgHAAQgEAAgEgCg");
	this.shape_48.setTransform(-289.95,-152.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQAMAAAHgHQAIgGgBgJQAAgFgCgFQgDgFgFgEQgEgDgQgKQgRgIgHgGQgIgFgDgHQgEgHAAgIQAAgPALgKQALgKARAAQAKAAALAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCACgEIADAAIAAAuIgDAAQgCgOgEgHQgFgIgJgFQgIgEgIAAQgKAAgHAGQgGAGAAAIQAAAGADAFQAHAHAWAMQASAKAHAFQAGAFAFAHQADAIAAAHQAAAQgLAKQgMALgTAAIgKgBg");
	this.shape_49.setTransform(-298.3,-152.775);

	this.instance_3 = new lib.Bitmap6();
	this.instance_3.setTransform(-296.05,-88,0.272,0.2692);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f().s("#000000").ss(1,1,1).p("ABE0dIWmAAMAAJAwlAXo8HIACHqIWmAAABB8HIADHqEguPgUdIX5AAIXaAAMAATAwlA2c8HIAGHqMAAmAwl");
	this.shape_50.setTransform(-10,0.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#CC3366").s().p("AXzcIMgAJgwlIWmAAMAAAAwlgABXcIMgATgwlI3ZAAIgHnqIAHHqI36AAIX6AAMAAlAwlI4fAAMAAAgwlIAAnqIXzAAIXdAAIWoAAIWnAAIAAHqI2mAAIgBnqIABHqI2mAAIgDnqIADHqIWmAAMAAJAwlgA1wcIMgAlgwlIXZAAMAATAwlgA2V0dg");
	this.shape_51.setTransform(-10,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_51},{t:this.shape_50},{t:this.instance_3},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.instance_2},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.instance_1},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.instance},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-306.9,-180.9,612.9,361.9);


(lib.Tween15 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCFFCC").s().p("AATAuIAAgTQgMANgGADQgFADgHAAQgHAAgGgEQgFgFgCgGQgCgHAAgMIAAgoQAAgGgCgDQgBgCgDgBQgDgBgHAAIAAgEIAgAAIAAA7QAAAMAEAFQAEADAHAAQADAAAFgCQAFgDAIgHIAAgyQAAgIgDgDQgDgCgJAAIAAgEIAfAAIAAA1QAAAQABADQAAAEACABQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAHgBIABADIgbALg");
	this.shape.setTransform(13.175,2.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCFFCC").s().p("AAFAuIAAgEIACAAQAGAAADgCQACgCABgDIAAgJIAAgkQABgMgEgGQgDgFgHAAQgLAAgMAMIAAAvQAAAJABACQACADACABQADABAHAAIAAAEIgsAAIAAgEIABAAQAHABADgEQACgDAAgKIAAggIgBgUIgCgFIgEgBIgGABIgCgDIAbgLIAEAAIAAATQAQgTANAAQAIAAAFAEQAFADAEAIQACAHAAALIAAAmQAAAJABADQAAAAABABQAAAAAAABQABAAAAAAQABABABAAQACABAGAAIAAAEg");
	this.shape_1.setTransform(3.2,1.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCFFCC").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_2.setTransform(-6.175,2.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCFFCC").s().p("AAdBCIAAgDIAFAAQAIAAADgFQACgEAAgLIAAhXIgxBuIgEAAIgzhuIAABXQAAANADADQADAEAIAAIAFAAIAAADIguAAIAAgDIAEAAQAJAAAEgFQACgEAAgLIAAhVQAAgJgCgEQgCgDgEgCQgDgCgIAAIAAgDIAmAAIAuBmIAvhmIAmAAIAAADIgFAAQgIAAgDAGQgCADAAALIAABVQAAANACADQAEAEAHAAIAFAAIAAADg");
	this.shape_3.setTransform(-19.65,-0.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("AqOjCIUdAAIAAGFI0dAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC3366").s().p("AqODDIAAmFIUdAAIAAGFg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-20.5,133,41);


(lib.Tween14 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCFFCC").s().p("AATAuIAAgTQgMANgGADQgFADgHAAQgHAAgGgEQgFgFgCgGQgCgHAAgMIAAgoQAAgGgCgDQgBgCgDgBQgDgBgHAAIAAgEIAgAAIAAA7QAAAMAEAFQAEADAHAAQADAAAFgCQAFgDAIgHIAAgyQAAgIgDgDQgDgCgJAAIAAgEIAfAAIAAA1QAAAQABADQAAAEACABQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAHgBIABADIgbALg");
	this.shape.setTransform(13.175,2.15);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#CCFFCC").s().p("AAFAuIAAgEIACAAQAGAAADgCQACgCABgDIAAgJIAAgkQABgMgEgGQgDgFgHAAQgLAAgMAMIAAAvQAAAJABACQACADACABQADABAHAAIAAAEIgsAAIAAgEIABAAQAHABADgEQACgDAAgKIAAggIgBgUIgCgFIgEgBIgGABIgCgDIAbgLIAEAAIAAATQAQgTANAAQAIAAAFAEQAFADAEAIQACAHAAALIAAAmQAAAJABADQAAAAABABQAAAAAAABQABAAAAAAQABABABAAQACABAGAAIAAAEg");
	this.shape_1.setTransform(3.2,1.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#CCFFCC").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_2.setTransform(-6.175,2.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CCFFCC").s().p("AAdBCIAAgDIAFAAQAIAAADgFQACgEAAgLIAAhXIgxBuIgEAAIgzhuIAABXQAAANADADQADAEAIAAIAFAAIAAADIguAAIAAgDIAEAAQAJAAAEgFQACgEAAgLIAAhVQAAgJgCgEQgCgDgEgCQgDgCgIAAIAAgDIAmAAIAuBmIAvhmIAmAAIAAADIgFAAQgIAAgDAGQgCADAAALIAABVQAAANACADQAEAEAHAAIAFAAIAAADg");
	this.shape_3.setTransform(-19.65,-0.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,1,1).p("AqOjCIUdAAIAAGFI0dAAg");

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#CC3366").s().p("AqODDIAAmFIUdAAIAAGFg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-66.5,-20.5,133,41);


(lib.Tween8 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap3();
	this.instance.setTransform(-61.25,-79.65,0.3024,0.2213);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-61.2,-79.6,122.4,159.3);


(lib.Tween6 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.text = new cjs.Text("A milkshake is a sweet, cold, blended beverage typically made with milk, ice cream, and flavorings or sweeteners. It originated in the United States around the turn of the 20th century and gained popularity with the introduction of electric blenders. ", "15px 'Lucida Handwriting'");
	this.text.lineHeight = 21;
	this.text.lineWidth = 342;
	this.text.parent = this;
	this.text.setTransform(-171,-94.85);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-173,-96.8,346,193.7);


(lib.start_button = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		playSound("rainyday");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(4));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDA6QgFgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAFgCAGgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAADgCQADgCACgEIAEAAQgEAKgGAEQgGAFgGAAQgFAAgDgCg");
	this.shape.setTransform(64.05,26.575);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAuIAAgDQAHAAAEgDQACgBABgDIABgKIAAgiQAAgQgBgCQAAgBgBgBQAAAAAAgBQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADADAAAFQAAAEgCACQgDADgDAAQgEAAgEgDQgEgEgCAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAIABADQABADADABQADADAGAAIAAADg");
	this.shape_1.setTransform(57.975,27.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMAsQgDgEAAgIQgNALgDABQgFADgGAAQgKAAgGgGQgGgHAAgKQAAgGADgGQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEAEAAAEIAAAFQAAAFgCACQgCADgEAAQgEAAgCgDQgCgCAAgFQAAgIAIgHQAJgHAQAAQAKAAAIAEQAGADADAGQABAFAAAMIAAAeIABAPIABAFIADABIADgBIAIgHIAAAFQgLAPgKAAQgFAAgDgDgAgJAAQgIAEgDAFQgDAEAAAGQAAAHAEAFQAEAEAGABQAHgBALgJIAAgiIgSAIg");
	this.shape_2.setTransform(50.375,27.95);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQAEAAADgCQADgCABgEIAEAAQgDAKgHAEQgGAFgHAAQgEAAgEgCg");
	this.shape_3.setTransform(42.95,26.575);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgIBEIgMgDIgMgDQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgCACAAAEIgEAAIAAgtIAEAAQACAOAEAHQAFAHAJAFQAJAFAJAAQANAAAGgHQAIgGAAgJQgBgFgCgFQgDgFgFgEIgUgNQgRgIgHgGQgHgFgFgHQgDgHAAgIQAAgPALgKQALgKARAAQAJAAAMAFIAIACQABAAAAAAQABAAAAAAQABAAAAgBQABAAAAAAQABgCABgEIAEAAIAAAuIgEAAQgBgOgEgHQgGgIgIgFQgIgEgIAAQgKAAgHAGQgGAGAAAIQAAAGADAFQAHAHAVAMQATAKAHAFQAGAFAEAHQAEAIAAAHQAAAQgLAKQgMALgTAAIgKgBg");
	this.shape_4.setTransform(34.6,25.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#993366").s().p("An4EJIAAoRIPxAAIAAIRg");
	this.shape_5.setTransform(50.5,26.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(3));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,101,53);


(lib.restart_button = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDA6QgFgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAADgCQAEgCABgEIAEAAQgDAKgHAEQgGAFgGAAQgFAAgDgCg");
	this.shape.setTransform(70,24.125);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAuIAAgEQAHAAAEgCQACgBABgDIABgKIAAgiQAAgPgBgDQAAgBgBgBQAAgBAAAAQAAgBgBAAQAAAAAAgBQgBAAAAAAQgBAAAAgBQgBAAgBAAQAAAAgBAAIgHABIAAgDIAbgLIAEAAIAAAUQAKgUAMAAQAFAAAEADQADAEAAAEQAAAEgCACQgDADgDAAQgEAAgEgEQgEgDgCAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAAAQgFAEgDAJIAAAqQAAAHABAFQABACADABQADACAGAAIAAAEg");
	this.shape_1.setTransform(63.925,25.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAMAsQgDgEAAgIQgNALgDACQgFACgGAAQgKAAgGgHQgGgGAAgKQAAgGADgGQAEgGAKgGQAKgFAWgJIAAgDQAAgNgEgFQgEgFgHAAQgHAAgDADQgEADAAAFIAAAFQAAAFgCADQgCACgEAAQgEAAgCgCQgCgDAAgFQAAgIAIgHQAJgHAQAAQAKAAAIAEQAGADADAGQABAEAAAOIAAAdIABAPIABAFIADABIADgBIAIgHIAAAFQgLAPgKAAQgFAAgDgDgAgJAAQgIAFgDAEQgDAFAAAFQAAAHAEAFQAEAEAGABQAHAAALgKIAAghIgSAHg");
	this.shape_2.setTransform(56.325,25.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgEA6QgEgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAGgCAFgFQAFgFAFgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQAEAAADgCQADgCABgEIAEAAQgDAKgHAEQgGAFgHAAQgEAAgEgCg");
	this.shape_3.setTransform(48.9,24.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRAtIgGgBQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAAAIgDAAIAAggIADAAQADAOAHAHQAIAHAIAAQAIAAADgEQAFgEAAgGQAAgGgFgFQgFgFgNgHQgOgGgFgFQgDgGAAgIQgBgLAIgIQAHgHANAAQAEAAAHACIAHABIACAAIACgDIAEAAIAAAeIgEAAQgEgOgFgFQgGgGgIAAQgHAAgEAEQgEAEAAAEQAAAGADADQADAEAJAFIANAHQAVAJgBAPQAAANgJAHQgJAHgMAAQgHAAgKgCg");
	this.shape_4.setTransform(42.25,25.525);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_5.setTransform(33.825,25.525);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAfBCIgsg+IgIABIgDAAIgDgBIAAAnQAAAMADADQADAFAIAAIAFAAIAAADIg5AAIAAgDIAFAAQAJAAADgGQACgDAAgLIAAhVQAAgMgDgDQgDgFgIAAIgFAAIAAgDIAwAAQAVAAAKADQAKADAHAIQAGAIAAAMQAAAMgHAJQgIAJgRADIAbAmQAKANAGAEQAHAEALACIAAADgAgbg4IAAA3IADAAIACAAQATAAAJgIQAKgIAAgNQAAgMgIgIQgIgIgMAAIgPACg");
	this.shape_6.setTransform(22.875,23.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#CC3366").s().p("AnVDwIAAnfIOrAAIAAHfg");
	this.shape_7.setTransform(46.975,24);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,94,48);


(lib.Next_button = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDA6QgFgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAFgCAGgFQAGgFAEgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAADgCQADgCACgEIAEAAQgEAKgGAEQgGAFgGAAQgFAAgDgCg");
	this.shape.setTransform(61.25,21.625);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAGAtIAAgEQAEAAACgCQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgDgGgJIgMgTIgPATQgGAJgBACQAAACADACQACACAEAAIAAAEIgdAAIAAgEQAEAAADgCIAMgPIASgYIgRgYQgHgLgEgCQgEgDgGAAIAAgEIArAAIAAAEQgFAAgBABQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAACADAFIADAFIAFAKIAIgKQAHgKAAgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIAAgEIAeAAIAAAEQgEAAgEADQgFADgJALIgLAQIAWAfQAIAMAEADQADACAGAAIAAAEg");
	this.shape_1.setTransform(53.35,23.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_2.setTransform(43.975,23.025);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAyBDIhXhpIAABQQAAANADADQAEAEAIAAIAEAAIAAADIguAAIAAgDIAFAAQAIAAAEgFQACgEAAgLIAAhbIgJgJIgJgEIgIgBIAAgDIAkAAIBQBiIAAhLQAAgMgDgDQgEgFgHAAIgFAAIAAgDIAuAAIAAADIgEAAQgJAAgDAGQgCADgBALIAABug");
	this.shape_3.setTransform(31.95,20.975);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#993366").s().p("AnzD5IAAnxIPnAAIAAHxg");
	this.shape_4.setTransform(49.975,24.875);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,100,49.8);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.button_2 = new lib.website_button();
	this.button_2.name = "button_2";
	this.button_2.setTransform(-2.45,0,1,1,0,0,0,47,24);
	new cjs.ButtonHelper(this.button_2, 0, 1, 2);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AnVA3IAAhtIOrAAIAABt");
	this.shape.setTransform(2.525,-18.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.button_2}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-49.4,-25,99.9,49), null);


// stage content:
(lib.project_edlyna = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,29,30,51,59];
	// timeline functions:
	this.frame_0 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
		
		/* Click to Go to Frame and Play
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and continues playback from that frame.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		this.start.addEventListener("click", fl_ClickToGoToAndPlayFromFrame.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame()
		{
			this.gotoAndPlay(1);
		}
		
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
	}
	this.frame_29 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
		
		
		/* Click to Go to Frame and Play
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and continues playback from that frame.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		this.Next_button.addEventListener("click", fl_ClickToGoToAndPlayFromFrame_2.bind(this));
		
		function fl_ClickToGoToAndPlayFromFrame_2()
		{
			this.gotoAndPlay(32);
		}
	}
	this.frame_30 = function() {
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.movieClip_3.addEventListener("click", fl_ClickToGoToWebPage_2);
		
		function fl_ClickToGoToWebPage_2() {
			window.open("https://nus.royalcakes.com/Category/signature-milkshakes.html/", "_blank");
		}
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.movieClip_3.addEventListener("click", fl_ClickToGoToWebPage_7);
		
		function fl_ClickToGoToWebPage_7() {
			window.open("https://nus.royalcakes.com/Category/signature-milkshakes.html", "_blank");
		}
	}
	this.frame_51 = function() {
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.movieClip_3.addEventListener("click", fl_ClickToGoToWebPage_6);
		
		function fl_ClickToGoToWebPage_6() {
			window.open("https://nus.royalcakes.com/Category/signature-milkshakes.html", "_blank");
		}
	}
	this.frame_59 = function() {
		/* Stop at This Frame
		The  timeline will stop/pause at the frame where you insert this code.
		Can also be used to stop/pause the timeline of movieclips.
		*/
		
		this.stop();
		
		/* Click to Go to Frame and Stop
		Clicking on the specified symbol instance moves the playhead to the specified frame in the timeline and stops the movie.
		Can be used on the main timeline or on movie clip timelines.
		
		Instructions:
		1. Replace the number 5 in the code below with the frame number you would like the playhead to move to when the symbol instance is clicked.
		2.Frame numbers in EaselJS start at 0 instead of 1
		*/
		
		
		this.restart_button.addEventListener("click", fl_ClickToGoToAndStopAtFrame_2.bind(this));
		
		function fl_ClickToGoToAndStopAtFrame_2()
		{
			this.gotoAndStop(5);
		}
		
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.movieClip_3.addEventListener("click", fl_ClickToGoToWebPage_5);
		
		function fl_ClickToGoToWebPage_5() {
			window.open("https://nus.royalcakes.com/Category/signature-milkshakes.html/", "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(29).call(this.frame_29).wait(1).call(this.frame_30).wait(21).call(this.frame_51).wait(8).call(this.frame_59).wait(1));

	// info_words
	this.instance = new lib.Tween6("synched",0);
	this.instance.setTransform(-185.3,274.15);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:531.95,y:458.8},29).to({_off:true},1).wait(30));

	// milkshake_layer
	this.instance_1 = new lib.Tween8("synched",0);
	this.instance_1.setTransform(-82.75,476.65);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:295.55,y:441.6},29).to({_off:true},1).wait(30));

	// object_layer
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(1,1,1).p("AhcgzIC5AAIAABnIi5AAg");
	this.shape.setTransform(461.375,433.05);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFCCCC").s().p("AhcA0IAAhnIC5AAIAABng");
	this.shape_1.setTransform(461.375,433.05);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("rgba(0,0,0,0.965)").ss(1,1,1).p("AiwhcIFZAAIAIAJIAACwIlZAAIgIgJg");
	this.shape_2.setTransform(461.375,433.05);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFCCCC").s().p("AioBcIgIgIIAAivIFZAAIAIAIIAACvg");
	this.shape_3.setTransform(461.375,433.05);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("rgba(0,0,0,0.929)").ss(1,1,1).p("AkDiEIH4AAIAPAIIAAEBIn4ABIgPgJg");
	this.shape_4.setTransform(461.375,433.05);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCCCC").s().p("AkDB9IAAkCIH4AAIAPAJIAAEBIn4AAg");
	this.shape_5.setTransform(461.375,433.05);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f().s("rgba(0,0,0,0.898)").ss(0.9,1,1).p("AlWitIKWAAIAXAIIAAFTIqWAAIgXgIg");
	this.shape_6.setTransform(461.375,433.05);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFCCCC").s().p("AlWCmIAAlTIKWAAIAXAIIAAFSIqWABg");
	this.shape_7.setTransform(461.375,433.05);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("rgba(0,0,0,0.863)").ss(0.9,1,1).p("AmqjWIM2AAIAfAIIAAGkIs2ABIgfgIg");
	this.shape_8.setTransform(461.375,433.05);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFCCCC").s().p("AmqDPIAAmlIM2AAIAfAIIAAGkIs2ABg");
	this.shape_9.setTransform(461.375,433.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f().s("rgba(0,0,0,0.827)").ss(0.9,1,1).p("An9j/IPVAAIAmAIIAAH1IvVACIgmgIg");
	this.shape_10.setTransform(461.375,433.05);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFCCCC").s().p("An9D4IAAn2IPVAAIAmAHIAAH1IvVACg");
	this.shape_11.setTransform(461.375,433.05);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("rgba(0,0,0,0.792)").ss(0.8,1,1).p("ApQknIR0AAIAtAHIAAJHIx0ABIgtgHg");
	this.shape_12.setTransform(461.375,433.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFCCCC").s().p("ApQEhIAApIIR0AAIAtAHIAAJHIx0ABg");
	this.shape_13.setTransform(461.375,433.025);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f().s("rgba(0,0,0,0.757)").ss(0.8,1,1).p("AqklQIUTAAIA2AHIAAKZI0TABIg2gHg");
	this.shape_14.setTransform(461.375,433.05);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFCCCC").s().p("AqkFKIAAqaIUTAAIA2AHIAAKYI0TACg");
	this.shape_15.setTransform(461.375,433.05);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f().s("rgba(0,0,0,0.725)").ss(0.7,1,1).p("Ar3l5IWyAAIA9AHIAALrI2yABIg9gHg");
	this.shape_16.setTransform(461.375,433.025);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFCCCC").s().p("Ar3FzIAArsIWyAAIA9AHIAALrI2yABg");
	this.shape_17.setTransform(461.375,433.025);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f().s("rgba(0,0,0,0.69)").ss(0.7,1,1).p("AtKmhIZRAAIBEAGIAAM8I5RACIhEgHg");
	this.shape_18.setTransform(461.375,433.05);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFCCCC").s().p("AtKGcIAAs9IZRAAIBEAFIAAM9I5RACg");
	this.shape_19.setTransform(461.375,433.05);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f().s("rgba(0,0,0,0.655)").ss(0.7,1,1).p("AuenKIbxAAIBMAGIAAOOI7xABIhMgGg");
	this.shape_20.setTransform(461.375,433.05);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFCCCC").s().p("AueHFIAAuPIbxAAIBMAGIAAONI7xACg");
	this.shape_21.setTransform(461.375,433.05);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("rgba(0,0,0,0.62)").ss(0.6,1,1).p("AvxnzIePAAIBUAGIAAPfI+PACIhUgGg");
	this.shape_22.setTransform(461.375,433.05);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFCCCC").s().p("AvxHuIAAvhIePAAIBUAFIAAPgI+PACg");
	this.shape_23.setTransform(461.375,433.05);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("rgba(0,0,0,0.584)").ss(0.6,1,1).p("AxEocMAguAAAIBbAFIAAQxMgguAADIhbgGg");
	this.shape_24.setTransform(461.375,433.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFCCCC").s().p("AxEIXIAAwzMAguAAAIBbAGIAAQwMgguAACg");
	this.shape_25.setTransform(461.375,433.05);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("rgba(0,0,0,0.553)").ss(0.6,1,1).p("AyYpEMAjOAAAIBjAFIAASCMgjOAACIhjgFg");
	this.shape_26.setTransform(461.375,433.025);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFCCCC").s().p("AyYJAIAAyEMAjOAAAIBjAFIAASCMgjOAACg");
	this.shape_27.setTransform(461.375,433.025);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("rgba(0,0,0,0.518)").ss(0.5,1,1).p("AzrptMAltAAAIBqAEIAATUMgltAADIhqgFg");
	this.shape_28.setTransform(461.375,433.05);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFCCCC").s().p("AzrJpIAAzWMAltAAAIBqAFIAATTMgltAADg");
	this.shape_29.setTransform(461.375,433.05);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f().s("rgba(0,0,0,0.482)").ss(0.5,1,1).p("A0+qWMAoLAAAIByAFIAAUlMgoLAADIhygEg");
	this.shape_30.setTransform(461.375,433.025);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFCCCC").s().p("A0+KTIAA0pMAoLAAAIByAFIAAUlMgoLAADg");
	this.shape_31.setTransform(461.375,433.025);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f().s("rgba(0,0,0,0.447)").ss(0.5,1,1).p("A2Sq+MAqrAAAIB6AEIAAV3IhHADMgpkAAAIh6gEg");
	this.shape_32.setTransform(461.375,433.05);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFCCCC").s().p("A0YK/Ih6gDIAA17MAqrAAAIB6AEIAAV4IhHACg");
	this.shape_33.setTransform(461.375,433.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f().s("rgba(0,0,0,0.416)").ss(0.4,1,1).p("A3lrnMAtKAAAICBAEIAAXIIhKADMgsAAAAIiBgDg");
	this.shape_34.setTransform(461.375,433.025);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFCCCC").s().p("A1kLoIiBgDIAA3MMAtKAAAICBAEIAAXIIhKADg");
	this.shape_35.setTransform(461.375,433.025);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f().s("rgba(0,0,0,0.38)").ss(0.4,1,1).p("A44sQMAxxAAEIAAYaIhOADMgubAAAIiIgDg");
	this.shape_36.setTransform(461.375,433.025);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFCCCC").s().p("A2wMRIiIgDIAA4eMAxxAAEIAAYaIhOADg");
	this.shape_37.setTransform(461.375,433.025);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f().s("rgba(0,0,0,0.345)").ss(0.4,1,1).p("A6Ms5MAyIAAAICRAEIAAZrIhTAEMgw1AAAIiRgDg");
	this.shape_38.setTransform(461.375,433.025);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFCCCC").s().p("A37M6IiRgDIAA5wMAyIAAAICRAEIAAZrIhTAEg");
	this.shape_39.setTransform(461.375,433.025);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f().s("rgba(0,0,0,0.31)").ss(0.3,1,1).p("A7fthMA2/AADIAAa9IhXADMg1ogACg");
	this.shape_40.setTransform(461.375,433.025);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFCCCC").s().p("A7fNgIAA7BMA2/AADIAAa9IhXADg");
	this.shape_41.setTransform(461.375,433.025);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f().s("rgba(0,0,0,0.275)").ss(0.3,1,1).p("A8yuKMA5lAADIAAcOIhaAEMg4LgADg");
	this.shape_42.setTransform(461.375,433.05);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFCCCC").s().p("A8yOJIAA8TMA5lAADIAAcOIhaAEg");
	this.shape_43.setTransform(461.375,433.05);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f().s("rgba(0,0,0,0.243)").ss(0.3,1,1).p("A+GuzMA8NAACIAAdhIhfAEMg6ugACg");
	this.shape_44.setTransform(461.375,433.025);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFCCCC").s().p("A+GOyIAA9lMA8NAACIAAdhIhfAEg");
	this.shape_45.setTransform(461.375,433.025);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f().s("rgba(0,0,0,0.208)").ss(0.2,1,1).p("A/ZvbMA+zAABIAAezIhjAEMg9QgACg");
	this.shape_46.setTransform(461.375,433.05);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFCCCC").s().p("A/ZPbIAA+3MA+zAACIAAezIhjADg");
	this.shape_47.setTransform(461.375,433.05);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f().s("rgba(0,0,0,0.173)").ss(0.2,1,1).p("EggtgQEMBBbAABMAAAAgEIhoAEMg/zgABg");
	this.shape_48.setTransform(461.375,433.025);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFCCCC").s().p("EggtAQEMAAAggIMBBbAABMAAAAgEIhoAEg");
	this.shape_49.setTransform(461.375,433.025);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f().s("rgba(0,0,0,0.137)").ss(0.2,1,1).p("EgiAgQtMBEBAABMAAAAhWIhrAEMhCWgABg");
	this.shape_50.setTransform(461.375,433.025);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFCCCC").s().p("EgiAAQtMAAAghaMBEBAABMAAAAhWIhrAEg");
	this.shape_51.setTransform(461.375,433.025);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f().s("rgba(0,0,0,0.102)").ss(0.1,1,1).p("EgjTgRWMBGnAABMAAAAinIhvAFMhE4gABg");
	this.shape_52.setTransform(461.375,433.025);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFCCCC").s().p("EgjTARWMAAAgisMBGnAABMAAAAinIhvAFg");
	this.shape_53.setTransform(461.375,433.025);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f().s("rgba(0,0,0,0.071)").ss(0.1,1,1).p("EgkngR+MBJPAAAMAAAAj5Ih0AEMhHbAAAg");
	this.shape_54.setTransform(461.375,433.025);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFCCCC").s().p("EgknAR/MAAAgj9MBJPAAAMAAAAj5Ih0AEg");
	this.shape_55.setTransform(461.375,433.025);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f().s("rgba(0,0,0,0.035)").ss(0.1,1,1).p("Egl6gSnMBL1AAAMAAAAlKIh4AFMhJ9AAAg");
	this.shape_56.setTransform(461.375,433.025);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFCCCC").s().p("Egl6ASoMAAAglPMBL1AAAMAAAAlKIh4AFg");
	this.shape_57.setTransform(461.375,433.025);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f().s("#000000").ss(1,1,1).p("EAlTATRMhKlAAAEglSgTQMBKlAAA");
	this.shape_58.setTransform(461.375,433.025);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFCCCC").s().p("EAlTATRMhKlAAAIh7AAMAAAgmhIB7AAMBKlAAAIB7AAMAAAAmhg");
	this.shape_59.setTransform(461.375,433.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_3},{t:this.shape_2}]},1).to({state:[{t:this.shape_5},{t:this.shape_4}]},1).to({state:[{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_9},{t:this.shape_8}]},1).to({state:[{t:this.shape_11},{t:this.shape_10}]},1).to({state:[{t:this.shape_13},{t:this.shape_12}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29},{t:this.shape_28}]},1).to({state:[{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_35},{t:this.shape_34}]},1).to({state:[{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},1).to({state:[{t:this.shape_41},{t:this.shape_40}]},1).to({state:[{t:this.shape_43},{t:this.shape_42}]},1).to({state:[{t:this.shape_45},{t:this.shape_44}]},1).to({state:[{t:this.shape_47},{t:this.shape_46}]},1).to({state:[{t:this.shape_49},{t:this.shape_48}]},1).to({state:[{t:this.shape_51},{t:this.shape_50}]},1).to({state:[{t:this.shape_53},{t:this.shape_52}]},1).to({state:[{t:this.shape_55},{t:this.shape_54}]},1).to({state:[{t:this.shape_57},{t:this.shape_56}]},1).to({state:[{t:this.shape_59},{t:this.shape_58}]},1).to({state:[]},1).wait(30));

	// start_button
	this.start = new lib.start_button();
	this.start.name = "start";
	this.start.setTransform(75.55,494.75,1,1,0,0,0,50.5,26.5);
	new cjs.ButtonHelper(this.start, 0, 1, 2, false, new lib.start_button(), 3);

	this.timeline.addTween(cjs.Tween.get(this.start).to({_off:true},30).wait(30));

	// Next_button
	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgDA6QgFgDgCgEQgCgFAAgKIAAg7IgOAAIAAgDQAFgCAGgFQAGgFAEgIIAFgNIADAAIAAAdIAVAAIAAAHIgVAAIAAA5QAAAJADADQACADAEAAQADAAADgCQADgCACgEIAEAAQgEAKgGAEQgGAFgGAAQgFAAgDgCg");
	this.shape_60.setTransform(87.35,555.125);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAGAtIAAgEQAEAAACgCQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAgDgGgJIgMgTIgPATQgGAJgBACQAAACADACQACACAEAAIAAAEIgdAAIAAgEQAEAAADgCIAMgPIASgYIgRgYQgHgLgEgCQgEgDgGAAIAAgEIArAAIAAAEQgFAAgBABQAAABgBAAQAAAAAAABQAAAAAAABQAAAAAAABQAAACADAFIADAFIAFAKIAIgKQAHgKAAgCQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQgCgBgDAAIAAgEIAeAAIAAAEQgFAAgDADQgFADgJALIgLAQIAWAfQAIAMAEADQADACAGAAIAAAEg");
	this.shape_61.setTransform(79.45,556.525);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgZAjQgMgNAAgVQAAgWAMgNQAMgMAQAAQAQAAAJAKQAKAJAAARIg9AAQAAATAKALQAJAMANAAQAIAAAHgFQAGgFAFgMIADACQgCAOgKALQgKAKgPAAQgPAAgLgMgAgPghQgHAGgBALIAoAAQAAgIgCgEQgCgFgFgDQgFgEgEAAQgIAAgGAHg");
	this.shape_62.setTransform(70.075,556.525);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AAyBDIhXhpIAABQQAAANADADQAEAEAIAAIAEAAIAAADIguAAIAAgDIAFAAQAIAAAEgFQACgEAAgLIAAhbIgJgJIgJgEIgIgBIAAgDIAkAAIBQBiIAAhLQAAgMgDgDQgEgFgHAAIgFAAIAAgDIAuAAIAAADIgFAAQgIAAgDAGQgCADgBALIAABug");
	this.shape_63.setTransform(58.05,554.475);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#993366").s().p("AnzD5IAAnxIPnAAIAAHxg");
	this.shape_64.setTransform(76.075,558.375);

	this.Next_button = new lib.Next_button();
	this.Next_button.name = "Next_button";
	this.Next_button.setTransform(76.1,558.4,1,1,0,0,0,50,24.9);
	new cjs.ButtonHelper(this.Next_button, 0, 1, 1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60}]}).to({state:[{t:this.Next_button}]},29).to({state:[]},1).wait(30));

	// bg
	this.text = new cjs.Text("Welcome to my cafe !", "30px 'Lucida Handwriting'", "#990066");
	this.text.lineHeight = 41;
	this.text.lineWidth = 359;
	this.text.parent = this;
	this.text.setTransform(349.95,209,1,1,-5.9487);

	this.instance_2 = new lib.pexelsjulieaagaard2467287();
	this.instance_2.setTransform(0,-9.1,0.2666,0.1528,0,0,0.4494);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.text}]}).to({state:[]},30).wait(30));

	// Menu_sign
	this.instance_3 = new lib.Tween14("synched",0);
	this.instance_3.setTransform(-222.45,137.55);
	this.instance_3._off = true;

	this.instance_4 = new lib.Tween15("synched",0);
	this.instance_4.setTransform(403.5,166.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_3}]},30).to({state:[{t:this.instance_4}]},4).wait(26));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(30).to({_off:false},0).to({_off:true,x:403.5,y:166.55},4).wait(26));

	// menu
	this.instance_5 = new lib.Tween16("synched",0);
	this.instance_5.setTransform(-314,361);
	this.instance_5._off = true;

	this.instance_6 = new lib.Tween17("synched",0);
	this.instance_6.setTransform(409.95,373);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.instance_5}]},30).to({state:[{t:this.instance_6}]},8).wait(22));
	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(30).to({_off:false},0).to({_off:true,x:409.95,y:373},8).wait(22));

	// website_button
	this.movieClip_3 = new lib.Symbol1();
	this.movieClip_3.name = "movieClip_3";
	this.movieClip_3.setTransform(750.7,527.8,1,1,0,0,0,0.2,-0.2);
	this.movieClip_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.movieClip_3).wait(30).to({_off:false},0).wait(30));

	// restart_button
	this.restart_button = new lib.restart_button();
	this.restart_button.name = "restart_button";
	this.restart_button.setTransform(748.05,465,1,1,0,0,0,47,24);
	new cjs.ButtonHelper(this.restart_button, 0, 1, 1);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f().s("#000000").ss(1,1,1).p("AnVAZIAAgxIOrAAIAAAx");
	this.shape_65.setTransform(759.975,554.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_65},{t:this.restart_button}]},30).wait(30));

	// bg_2
	this.instance_7 = new lib.Bitmap4();
	this.instance_7.setTransform(-10,-9,0.7351,0.8639);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AreJYIAAyvIW9AAIAASvg");
	this.shape_66.setTransform(166.5,195.05);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_66},{t:this.instance_7}]},30).wait(30));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(-221,290.9,1038,348);
// library properties:
lib.properties = {
	id: '235A793C0B578E4CAB77BC22E70CB1A2',
	width: 800,
	height: 600,
	fps: 25,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/project_edlyna_atlas_1.png", id:"project_edlyna_atlas_1"},
		{src:"sounds/rainyday.mp3", id:"rainyday"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['235A793C0B578E4CAB77BC22E70CB1A2'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;